// PC Sound data generated by ckaudext by John314
// 

const unsigned int SND1_044_length = 9;
const unsigned short SND1_044_priority = 99;
const unsigned char SND1_044_data[] = {
	0x8a, 0x5f, 0x64, 0x9c, 0x46, 0x46, 0x9b, 0x88, 0x89, 
};
