// PC Sound data generated by ckaudext by John314
// 

const unsigned int SND1_049_length = 7;
const unsigned short SND1_049_priority = 0;
const unsigned char SND1_049_data[] = {
	0x17, 0x17, 0x17, 0x17, 0x17, 0x17, 0x17, 
};
