// PC Sound data generated by ckaudext by John314
// 

const unsigned int SND1_048_length = 7;
const unsigned short SND1_048_priority = 0;
const unsigned char SND1_048_data[] = {
	0x41, 0x41, 0x41, 0x41, 0x41, 0x41, 0x41, 
};
