// PC Sound data generated by ckaudext by John314
// 

const unsigned int SND1_015_length = 4;
const unsigned short SND1_015_priority = 60;
const unsigned char SND1_015_data[] = {
	0x17, 0x17, 0x17, 0x19, 
};
