// PC Sound data generated by ckaudext by John314
// 

const unsigned int SND1_000_length = 4;
const unsigned short SND1_000_priority = 20;
const unsigned char SND1_000_data[] = {
	0x87, 0x87, 0x87, 0x87, 
};
