// PC Sound data generated by psnd2gba by John314
// 
const unsigned int SND1_001_length = 4;
const unsigned short SND1_001_priority = 20;
const unsigned char SND1_001_data[] = {
	0x8c, 0x8c, 0x8c, 0x8c, 0x0, 0x0, 
};
