// PC Sound data generated by ckaudext by John314
// 

const unsigned int SND1_047_length = 7;
const unsigned short SND1_047_priority = 0;
const unsigned char SND1_047_data[] = {
	0x14, 0x14, 0x14, 0x14, 0x14, 0x14, 0x14, 
};
