// PC Sound data generated by psnd2gba by John314
// 
const unsigned int SND1_047_length = 7;
const unsigned short SND1_047_priority = 0;
const unsigned char SND1_047_data[] = {
	0x14, 0x14, 0x14, 0x14, 0x14, 0x14, 0x14, 0x0, 0x0, 
};
