/*
 * ckdemomk - Written by John314
 * 
 * Compile: g++ ckdemomk.cpp  -o ckdemomk
 * 
 * Converts a keen demo to a useable format for the GBA
 * 
*/

#include <stdio.h>
#include <iostream>
#include <iomanip>
#include <vector>
#include <string>
#include <cstring>
#include <fstream>
#include <cstdint>



int main(int argc, char *args[]){

	if(argc < 2){
		std::cout << "Error! Bad number of args!" << std::endl;
		std::cout << "Use: ckdemomk DEMOn.CKx <exportdir>" << std::endl;
		return 0;
	}
	
	std::string filename;
	int fnamestart = 0;
	for(int i = strlen(args[1])-1; i >= 0; i--){
		if(args[1][i] == '/') {
			fnamestart = i+1;
			break;
		}
	}
	for(int i = fnamestart; i < strlen(args[1]); i++){
		if(args[1][i] == '.') break;
		filename.push_back(args[1][i]);
	}
	
	std::ifstream DemoFile;
	DemoFile.open(args[1]);
	if(!DemoFile.is_open()){
		std::cerr << "Could not open text file: " << args[1] << std::endl;
		return 1;
	}

	std::ofstream DemoOutF;
	std::string DemoWName = ""; 
	if(argc > 2){
		DemoWName = args[2];
	}
	DemoWName += filename+".c";
	
	DemoOutF.open(DemoWName);
	if(DemoOutF.is_open()){
		DemoOutF << "// Generated by ckdemomk by John314\n";
		DemoOutF << "// \n";
		DemoOutF << "const unsigned char CK_" << filename << "_data[] = {";
		int count = 0;
		while(!DemoFile.eof()){
			if((count%16) == 0){
				DemoOutF << "\n\t";
			}
			count++;
			unsigned char data;
			DemoFile.read((char*)&data,1);
			DemoOutF << "0x" << std::hex << (int)data << ", ";
		}
		DemoOutF << "};\n";
	}
	DemoOutF.close();
	DemoFile.close();
	
	return 0;
};

