import re

outfile = open("state_defs.h", "w+")

outfile.write("// State list generated by makestatelist.py\n")
outfile.write("const statetype* CK_StateList[] = {")

chunkid = 0
foundstart = False

with open("ck_states.h") as gfxfile:
    line_count = 0
    for line in gfxfile:
        clean_line = line[0 : len(line)-1].strip()
        if len(clean_line):
            if(clean_line[0]!='#' and clean_line[0]!='/'):
                statename = clean_line[23 : len(clean_line)-1]
                if( (line_count%16) == 0):
                    outfile.write("\n\t")
                outfile.write("&"+statename+", ")
                line_count+=1
            else:
                if(clean_line[0]!='/'):
                    outfile.write("\n"+clean_line)
                else:
                    outfile.write("\n\t"+clean_line)
                line_count = 0

outfile.write("\n\tnil // Needed for end of list\n};\n")
outfile.close()

