// Music Info Header generated by ckaudext by John314
// 

const unsigned int SND1_156_size = 222058;
extern const unsigned char SND1_156_data[];
const unsigned int SND1_157_size = 568817;
extern const unsigned char SND1_157_data[];
const unsigned int SND1_158_size = 171993;
extern const unsigned char SND1_158_data[];
const unsigned int SND1_159_size = 482265;
extern const unsigned char SND1_159_data[];
const unsigned int SND1_160_size = 348698;
extern const unsigned char SND1_160_data[];
const unsigned int SND1_161_size = 136523;
extern const unsigned char SND1_161_data[];
const GBA_SoundSample CKM_GBA_Samples [] = {
	{&SND1_156_data , SND1_156_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{&SND1_157_data , SND1_157_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{&SND1_158_data , SND1_158_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{&SND1_159_data , SND1_159_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{&SND1_160_data , SND1_160_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{&SND1_161_data , SND1_161_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
};
