// Sound definitions generated by gensndhead.py

extern const unsigned int SND1_019_length;
extern const unsigned char SND1_019_data[];
extern const unsigned int SND1_000_length;
extern const unsigned char SND1_000_data[];
extern const unsigned int SND1_001_length;
extern const unsigned char SND1_001_data[];
extern const unsigned int SND1_002_length;
extern const unsigned char SND1_002_data[];
extern const unsigned int SND1_003_length;
extern const unsigned char SND1_003_data[];
extern const unsigned int SND1_004_length;
extern const unsigned char SND1_004_data[];
extern const unsigned int SND1_005_length;
extern const unsigned char SND1_005_data[];
extern const unsigned int SND1_006_length;
extern const unsigned char SND1_006_data[];
extern const unsigned int SND1_007_length;
extern const unsigned char SND1_007_data[];
extern const unsigned int SND1_008_length;
extern const unsigned char SND1_008_data[];
extern const unsigned int SND1_009_length;
extern const unsigned char SND1_009_data[];
extern const unsigned int SND1_010_length;
extern const unsigned char SND1_010_data[];
extern const unsigned int SND1_011_length;
extern const unsigned char SND1_011_data[];
extern const unsigned int SND1_012_length;
extern const unsigned char SND1_012_data[];
extern const unsigned int SND1_013_length;
extern const unsigned char SND1_013_data[];
extern const unsigned int SND1_014_length;
extern const unsigned char SND1_014_data[];
extern const unsigned int SND1_015_length;
extern const unsigned char SND1_015_data[];
extern const unsigned int SND1_016_length;
extern const unsigned char SND1_016_data[];
extern const unsigned int SND1_017_length;
extern const unsigned char SND1_017_data[];
extern const unsigned int SND1_018_length;
extern const unsigned char SND1_018_data[];
extern const unsigned int SND1_020_length;
extern const unsigned char SND1_020_data[];
extern const unsigned int SND1_021_length;
extern const unsigned char SND1_021_data[];
extern const unsigned int SND1_022_length;
extern const unsigned char SND1_022_data[];
extern const unsigned int SND1_023_length;
extern const unsigned char SND1_023_data[];
extern const unsigned int SND1_024_length;
extern const unsigned char SND1_024_data[];
extern const unsigned int SND1_025_length;
extern const unsigned char SND1_025_data[];
extern const unsigned int SND1_026_length;
extern const unsigned char SND1_026_data[];
extern const unsigned int SND1_027_length;
extern const unsigned char SND1_027_data[];
extern const unsigned int SND1_028_length;
extern const unsigned char SND1_028_data[];
extern const unsigned int SND1_029_length;
extern const unsigned char SND1_029_data[];
extern const unsigned int SND1_030_length;
extern const unsigned char SND1_030_data[];
extern const unsigned int SND1_031_length;
extern const unsigned char SND1_031_data[];
extern const unsigned int SND1_032_length;
extern const unsigned char SND1_032_data[];
extern const unsigned int SND1_033_length;
extern const unsigned char SND1_033_data[];
extern const unsigned int SND1_034_length;
extern const unsigned char SND1_034_data[];
extern const unsigned int SND1_035_length;
extern const unsigned char SND1_035_data[];
extern const unsigned int SND1_036_length;
extern const unsigned char SND1_036_data[];
extern const unsigned int SND1_037_length;
extern const unsigned char SND1_037_data[];
extern const unsigned int SND1_038_length;
extern const unsigned char SND1_038_data[];
extern const unsigned int SND1_039_length;
extern const unsigned char SND1_039_data[];
extern const unsigned int SND1_040_length;
extern const unsigned char SND1_040_data[];
extern const unsigned int SND1_041_length;
extern const unsigned char SND1_041_data[];
extern const unsigned int SND1_042_length;
extern const unsigned char SND1_042_data[];
extern const unsigned int SND1_043_length;
extern const unsigned char SND1_043_data[];
extern const unsigned int SND1_044_length;
extern const unsigned char SND1_044_data[];
extern const unsigned int SND1_045_length;
extern const unsigned char SND1_045_data[];
extern const unsigned int SND1_046_length;
extern const unsigned char SND1_046_data[];
extern const unsigned int SND1_047_length;
extern const unsigned char SND1_047_data[];
extern const unsigned int SND1_048_length;
extern const unsigned char SND1_048_data[];
extern const unsigned int SND1_049_length;
extern const unsigned char SND1_049_data[];
extern const unsigned int SND1_050_length;
extern const unsigned char SND1_050_data[];
extern const unsigned int SND1_051_length;
extern const unsigned char SND1_051_data[];


const unsigned char *CKS_PC_Samples [] = {
	&SND1_019_data,
	&SND1_000_data,
	&SND1_001_data,
	&SND1_002_data,
	&SND1_003_data,
	&SND1_004_data,
	&SND1_005_data,
	&SND1_006_data,
	&SND1_007_data,
	&SND1_008_data,
	&SND1_009_data,
	&SND1_010_data,
	&SND1_011_data,
	&SND1_012_data,
	&SND1_013_data,
	&SND1_014_data,
	&SND1_015_data,
	&SND1_016_data,
	&SND1_017_data,
	&SND1_018_data,
	&SND1_020_data,
	&SND1_021_data,
	&SND1_022_data,
	&SND1_023_data,
	&SND1_024_data,
	&SND1_025_data,
	&SND1_026_data,
	&SND1_027_data,
	&SND1_028_data,
	&SND1_029_data,
	&SND1_030_data,
	&SND1_031_data,
	&SND1_032_data,
	&SND1_033_data,
	&SND1_034_data,
	&SND1_035_data,
	&SND1_036_data,
	&SND1_037_data,
	&SND1_038_data,
	&SND1_039_data,
	&SND1_040_data,
	&SND1_041_data,
	&SND1_042_data,
	&SND1_043_data,
	&SND1_044_data,
	&SND1_045_data,
	&SND1_046_data,
	&SND1_047_data,
	&SND1_048_data,
	&SND1_049_data,
	&SND1_050_data,
	&SND1_051_data,
};

