// Sound definitions generated by gensndhead.py

const unsigned int SND1_052_size = 391;
extern const unsigned char SND1_052_data[];
const unsigned int SND1_053_size = 703;
extern const unsigned char SND1_053_data[];
const unsigned int SND1_054_size = 3667;
extern const unsigned char SND1_054_data[];
const unsigned int SND1_055_size = 1795;
extern const unsigned char SND1_055_data[];
const unsigned int SND1_056_size = 5383;
extern const unsigned char SND1_056_data[];
const unsigned int SND1_057_size = 1639;
extern const unsigned char SND1_057_data[];
const unsigned int SND1_058_size = 5071;
extern const unsigned char SND1_058_data[];
const unsigned int SND1_059_size = 4759;
extern const unsigned char SND1_059_data[];
const unsigned int SND1_060_size = 2419;
extern const unsigned char SND1_060_data[];
const unsigned int SND1_061_size = 6319;
extern const unsigned char SND1_061_data[];
const unsigned int SND1_062_size = 2419;
extern const unsigned char SND1_062_data[];
const unsigned int SND1_063_size = 4135;
extern const unsigned char SND1_063_data[];
const unsigned int SND1_064_size = 13963;
extern const unsigned char SND1_064_data[];
const unsigned int SND1_065_size = 18799;
extern const unsigned char SND1_065_data[];
const unsigned int SND1_066_size = 2887;
extern const unsigned char SND1_066_data[];
const unsigned int SND1_067_size = 391;
extern const unsigned char SND1_067_data[];
const unsigned int SND1_068_size = 2887;
extern const unsigned char SND1_068_data[];
const unsigned int SND1_069_size = 21139;
extern const unsigned char SND1_069_data[];
const unsigned int SND1_070_size = 3823;
extern const unsigned char SND1_070_data[];
const unsigned int SND1_071_size = 6007;
extern const unsigned char SND1_071_data[];
const unsigned int SND1_072_size = 4603;
extern const unsigned char SND1_072_data[];
const unsigned int SND1_073_size = 1327;
extern const unsigned char SND1_073_data[];
const unsigned int SND1_074_size = 2107;
extern const unsigned char SND1_074_data[];
const unsigned int SND1_075_size = 22231;
extern const unsigned char SND1_075_data[];
const unsigned int SND1_076_size = 3667;
extern const unsigned char SND1_076_data[];
const unsigned int SND1_077_size = 3823;
extern const unsigned char SND1_077_data[];
const unsigned int SND1_078_size = 2107;
extern const unsigned char SND1_078_data[];
const unsigned int SND1_079_size = 3511;
extern const unsigned char SND1_079_data[];
const unsigned int SND1_080_size = 3355;
extern const unsigned char SND1_080_data[];
const unsigned int SND1_081_size = 2887;
extern const unsigned char SND1_081_data[];
const unsigned int SND1_082_size = 4291;
extern const unsigned char SND1_082_data[];
const unsigned int SND1_083_size = 12871;
extern const unsigned char SND1_083_data[];
const unsigned int SND1_084_size = 7255;
extern const unsigned char SND1_084_data[];
const unsigned int SND1_085_size = 6475;
extern const unsigned char SND1_085_data[];
const unsigned int SND1_086_size = 5227;
extern const unsigned char SND1_086_data[];
const unsigned int SND1_087_size = 6787;
extern const unsigned char SND1_087_data[];
const unsigned int SND1_088_size = 2263;
extern const unsigned char SND1_088_data[];
const unsigned int SND1_089_size = 8815;
extern const unsigned char SND1_089_data[];
const unsigned int SND1_090_size = 3979;
extern const unsigned char SND1_090_data[];
const unsigned int SND1_091_size = 9595;
extern const unsigned char SND1_091_data[];
const unsigned int SND1_092_size = 8815;
extern const unsigned char SND1_092_data[];
const unsigned int SND1_093_size = 2107;
extern const unsigned char SND1_093_data[];
const unsigned int SND1_094_size = 5383;
extern const unsigned char SND1_094_data[];
const unsigned int SND1_095_size = 2419;
extern const unsigned char SND1_095_data[];
const unsigned int SND1_096_size = 703;
extern const unsigned char SND1_096_data[];
const unsigned int SND1_097_size = 11623;
extern const unsigned char SND1_097_data[];
const unsigned int SND1_098_size = 5071;
extern const unsigned char SND1_098_data[];
const unsigned int SND1_099_size = 703;
extern const unsigned char SND1_099_data[];
const unsigned int SND1_100_size = 703;
extern const unsigned char SND1_100_data[];
const unsigned int SND1_101_size = 703;
extern const unsigned char SND1_101_data[];
const unsigned int SND1_102_size = 3355;
extern const unsigned char SND1_102_data[];
const unsigned int SND1_103_size = 6007;
extern const unsigned char SND1_103_data[];


const GBA_SoundSample CKS_GBA_Samples [] = {
	{ &SND1_052_data, SND1_052_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_053_data, SND1_053_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_054_data, SND1_054_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_055_data, SND1_055_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_056_data, SND1_056_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_057_data, SND1_057_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_058_data, SND1_058_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_059_data, SND1_059_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_060_data, SND1_060_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_061_data, SND1_061_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_062_data, SND1_062_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_063_data, SND1_063_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_064_data, SND1_064_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_065_data, SND1_065_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_066_data, SND1_066_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_067_data, SND1_067_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_068_data, SND1_068_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_069_data, SND1_069_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_070_data, SND1_070_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_071_data, SND1_071_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_072_data, SND1_072_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_073_data, SND1_073_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_074_data, SND1_074_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_075_data, SND1_075_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_076_data, SND1_076_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_077_data, SND1_077_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_078_data, SND1_078_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_079_data, SND1_079_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_080_data, SND1_080_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_081_data, SND1_081_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_082_data, SND1_082_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_083_data, SND1_083_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_084_data, SND1_084_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_085_data, SND1_085_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_086_data, SND1_086_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_087_data, SND1_087_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_088_data, SND1_088_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_089_data, SND1_089_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_090_data, SND1_090_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_091_data, SND1_091_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_092_data, SND1_092_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_093_data, SND1_093_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_094_data, SND1_094_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_095_data, SND1_095_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_096_data, SND1_096_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_097_data, SND1_097_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_098_data, SND1_098_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_099_data, SND1_099_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_100_data, SND1_100_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_101_data, SND1_101_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_102_data, SND1_102_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
	{ &SND1_103_data, SND1_103_size, GBA_INV_11025, GBA_SAMP_RATE_11025 },
};

