// Sprite GBA sheet generated by ckspr2sheet bu John314
//
extern const unsigned int CKS_Paddle_width;
extern const unsigned int CKS_Paddle_height;
extern const unsigned int CKS_Paddle_size;
extern const unsigned char CKS_Paddle_data[];
extern const unsigned short CKS_Paddle_boxinfo[];
extern const unsigned int CKS_Paddle_SprSize;
extern const unsigned int CKS_Paddle_SprCount;
extern const unsigned int CKS_Paddle_SprData[];
extern const unsigned int CKS_Ball_width;
extern const unsigned int CKS_Ball_height;
extern const unsigned int CKS_Ball_size;
extern const unsigned char CKS_Ball_data[];
extern const unsigned short CKS_Ball_boxinfo[];
extern const unsigned int CKS_Ball_SprSize;
extern const unsigned int CKS_Ball_SprCount;
extern const unsigned int CKS_Ball_SprData[];
extern const unsigned int CKS_Demo_width;
extern const unsigned int CKS_Demo_height;
extern const unsigned int CKS_Demo_size;
extern const unsigned char CKS_Demo_data[];
extern const unsigned short CKS_Demo_boxinfo[];
extern const unsigned int CKS_Demo_SprSize;
extern const unsigned int CKS_Demo_SprCount;
extern const unsigned int CKS_Demo_SprData[];
extern const unsigned int CKS_Keen_width;
extern const unsigned int CKS_Keen_height;
extern const unsigned int CKS_Keen_size;
extern const unsigned char CKS_Keen_data[];
extern const unsigned short CKS_Keen_boxinfo[];
extern const unsigned int CKS_Keen_SprSize;
extern const unsigned int CKS_Keen_SprCount;
extern const unsigned int CKS_Keen_SprData[];
extern const unsigned int CKS_Stars_width;
extern const unsigned int CKS_Stars_height;
extern const unsigned int CKS_Stars_size;
extern const unsigned char CKS_Stars_data[];
extern const unsigned short CKS_Stars_boxinfo[];
extern const unsigned int CKS_Stars_SprSize;
extern const unsigned int CKS_Stars_SprCount;
extern const unsigned int CKS_Stars_SprData[];
extern const unsigned int CKS_Shot_width;
extern const unsigned int CKS_Shot_height;
extern const unsigned int CKS_Shot_size;
extern const unsigned char CKS_Shot_data[];
extern const unsigned short CKS_Shot_boxinfo[];
extern const unsigned int CKS_Shot_SprSize;
extern const unsigned int CKS_Shot_SprCount;
extern const unsigned int CKS_Shot_SprData[];
extern const unsigned int CKS_Droplets_width;
extern const unsigned int CKS_Droplets_height;
extern const unsigned int CKS_Droplets_size;
extern const unsigned char CKS_Droplets_data[];
extern const unsigned short CKS_Droplets_boxinfo[];
extern const unsigned int CKS_Droplets_SprSize;
extern const unsigned int CKS_Droplets_SprCount;
extern const unsigned int CKS_Droplets_SprData[];
extern const unsigned int CKS_OneUp_width;
extern const unsigned int CKS_OneUp_height;
extern const unsigned int CKS_OneUp_size;
extern const unsigned char CKS_OneUp_data[];
extern const unsigned short CKS_OneUp_boxinfo[];
extern const unsigned int CKS_OneUp_SprSize;
extern const unsigned int CKS_OneUp_SprCount;
extern const unsigned int CKS_OneUp_SprData[];
extern const unsigned int CKS_Shadows_width;
extern const unsigned int CKS_Shadows_height;
extern const unsigned int CKS_Shadows_size;
extern const unsigned char CKS_Shadows_data[];
extern const unsigned short CKS_Shadows_boxinfo[];
extern const unsigned int CKS_Shadows_SprSize;
extern const unsigned int CKS_Shadows_SprCount;
extern const unsigned int CKS_Shadows_SprData[];
extern const unsigned int CKS_Soda_width;
extern const unsigned int CKS_Soda_height;
extern const unsigned int CKS_Soda_size;
extern const unsigned char CKS_Soda_data[];
extern const unsigned short CKS_Soda_boxinfo[];
extern const unsigned int CKS_Soda_SprSize;
extern const unsigned int CKS_Soda_SprCount;
extern const unsigned int CKS_Soda_SprData[];
extern const unsigned int CKS_TTGum_width;
extern const unsigned int CKS_TTGum_height;
extern const unsigned int CKS_TTGum_size;
extern const unsigned char CKS_TTGum_data[];
extern const unsigned short CKS_TTGum_boxinfo[];
extern const unsigned int CKS_TTGum_SprSize;
extern const unsigned int CKS_TTGum_SprCount;
extern const unsigned int CKS_TTGum_SprData[];
extern const unsigned int CKS_CBar_width;
extern const unsigned int CKS_CBar_height;
extern const unsigned int CKS_CBar_size;
extern const unsigned char CKS_CBar_data[];
extern const unsigned short CKS_CBar_boxinfo[];
extern const unsigned int CKS_CBar_SprSize;
extern const unsigned int CKS_CBar_SprCount;
extern const unsigned int CKS_CBar_SprData[];
extern const unsigned int CKS_JBreaker_width;
extern const unsigned int CKS_JBreaker_height;
extern const unsigned int CKS_JBreaker_size;
extern const unsigned char CKS_JBreaker_data[];
extern const unsigned short CKS_JBreaker_boxinfo[];
extern const unsigned int CKS_JBreaker_SprSize;
extern const unsigned int CKS_JBreaker_SprCount;
extern const unsigned int CKS_JBreaker_SprData[];
extern const unsigned int CKS_Doughnut_width;
extern const unsigned int CKS_Doughnut_height;
extern const unsigned int CKS_Doughnut_size;
extern const unsigned char CKS_Doughnut_data[];
extern const unsigned short CKS_Doughnut_boxinfo[];
extern const unsigned int CKS_Doughnut_SprSize;
extern const unsigned int CKS_Doughnut_SprCount;
extern const unsigned int CKS_Doughnut_SprData[];
extern const unsigned int CKS_Icecream_width;
extern const unsigned int CKS_Icecream_height;
extern const unsigned int CKS_Icecream_size;
extern const unsigned char CKS_Icecream_data[];
extern const unsigned short CKS_Icecream_boxinfo[];
extern const unsigned int CKS_Icecream_SprSize;
extern const unsigned int CKS_Icecream_SprCount;
extern const unsigned int CKS_Icecream_SprData[];
extern const unsigned int CKS_LWFlask_width;
extern const unsigned int CKS_LWFlask_height;
extern const unsigned int CKS_LWFlask_size;
extern const unsigned char CKS_LWFlask_data[];
extern const unsigned short CKS_LWFlask_boxinfo[];
extern const unsigned int CKS_LWFlask_SprSize;
extern const unsigned int CKS_LWFlask_SprCount;
extern const unsigned int CKS_LWFlask_SprData[];
extern const unsigned int CKS_Door_width;
extern const unsigned int CKS_Door_height;
extern const unsigned int CKS_Door_size;
extern const unsigned char CKS_Door_data[];
extern const unsigned short CKS_Door_boxinfo[];
extern const unsigned int CKS_Door_SprSize;
extern const unsigned int CKS_Door_SprCount;
extern const unsigned int CKS_Door_SprData[];
extern const unsigned int CKS_RKey_width;
extern const unsigned int CKS_RKey_height;
extern const unsigned int CKS_RKey_size;
extern const unsigned char CKS_RKey_data[];
extern const unsigned short CKS_RKey_boxinfo[];
extern const unsigned int CKS_RKey_SprSize;
extern const unsigned int CKS_RKey_SprCount;
extern const unsigned int CKS_RKey_SprData[];
extern const unsigned int CKS_YKey_width;
extern const unsigned int CKS_YKey_height;
extern const unsigned int CKS_YKey_size;
extern const unsigned char CKS_YKey_data[];
extern const unsigned short CKS_YKey_boxinfo[];
extern const unsigned int CKS_YKey_SprSize;
extern const unsigned int CKS_YKey_SprCount;
extern const unsigned int CKS_YKey_SprData[];
extern const unsigned int CKS_BKey_width;
extern const unsigned int CKS_BKey_height;
extern const unsigned int CKS_BKey_size;
extern const unsigned char CKS_BKey_data[];
extern const unsigned short CKS_BKey_boxinfo[];
extern const unsigned int CKS_BKey_SprSize;
extern const unsigned int CKS_BKey_SprCount;
extern const unsigned int CKS_BKey_SprData[];
extern const unsigned int CKS_GKey_width;
extern const unsigned int CKS_GKey_height;
extern const unsigned int CKS_GKey_size;
extern const unsigned char CKS_GKey_data[];
extern const unsigned short CKS_GKey_boxinfo[];
extern const unsigned int CKS_GKey_SprSize;
extern const unsigned int CKS_GKey_SprCount;
extern const unsigned int CKS_GKey_SprData[];
extern const unsigned int CKS_KeyShadow_width;
extern const unsigned int CKS_KeyShadow_height;
extern const unsigned int CKS_KeyShadow_size;
extern const unsigned char CKS_KeyShadow_data[];
extern const unsigned short CKS_KeyShadow_boxinfo[];
extern const unsigned int CKS_KeyShadow_SprSize;
extern const unsigned int CKS_KeyShadow_SprCount;
extern const unsigned int CKS_KeyShadow_SprData[];
extern const unsigned int CKS_NStunner_width;
extern const unsigned int CKS_NStunner_height;
extern const unsigned int CKS_NStunner_size;
extern const unsigned char CKS_NStunner_data[];
extern const unsigned short CKS_NStunner_boxinfo[];
extern const unsigned int CKS_NStunner_SprSize;
extern const unsigned int CKS_NStunner_SprCount;
extern const unsigned int CKS_NStunner_SprData[];
extern const unsigned int CKS_ScoreBox_width;
extern const unsigned int CKS_ScoreBox_height;
extern const unsigned int CKS_ScoreBox_size;
extern const unsigned char CKS_ScoreBox_data[];
extern const unsigned short CKS_ScoreBox_boxinfo[];
extern const unsigned int CKS_ScoreBox_SprSize;
extern const unsigned int CKS_ScoreBox_SprCount;
extern const unsigned int CKS_ScoreBox_SprData[];
extern const unsigned int CKS_MapKeen_width;
extern const unsigned int CKS_MapKeen_height;
extern const unsigned int CKS_MapKeen_size;
extern const unsigned char CKS_MapKeen_data[];
extern const unsigned short CKS_MapKeen_boxinfo[];
extern const unsigned int CKS_MapKeen_SprSize;
extern const unsigned int CKS_MapKeen_SprCount;
extern const unsigned int CKS_MapKeen_SprData[];
extern const unsigned int CKS_MapFoot_width;
extern const unsigned int CKS_MapFoot_height;
extern const unsigned int CKS_MapFoot_size;
extern const unsigned char CKS_MapFoot_data[];
extern const unsigned short CKS_MapFoot_boxinfo[];
extern const unsigned int CKS_MapFoot_SprSize;
extern const unsigned int CKS_MapFoot_SprCount;
extern const unsigned int CKS_MapFoot_SprData[];
extern const unsigned int CKS_MapFlagFlip_width;
extern const unsigned int CKS_MapFlagFlip_height;
extern const unsigned int CKS_MapFlagFlip_size;
extern const unsigned char CKS_MapFlagFlip_data[];
extern const unsigned short CKS_MapFlagFlip_boxinfo[];
extern const unsigned int CKS_MapFlagFlip_SprSize;
extern const unsigned int CKS_MapFlagFlip_SprCount;
extern const unsigned int CKS_MapFlagFlip_SprData[];
extern const unsigned int CKS_MapFlagIdle_width;
extern const unsigned int CKS_MapFlagIdle_height;
extern const unsigned int CKS_MapFlagIdle_size;
extern const unsigned char CKS_MapFlagIdle_data[];
extern const unsigned short CKS_MapFlagIdle_boxinfo[];
extern const unsigned int CKS_MapFlagIdle_SprSize;
extern const unsigned int CKS_MapFlagIdle_SprCount;
extern const unsigned int CKS_MapFlagIdle_SprData[];
extern const unsigned int CKS_KeenSwim_width;
extern const unsigned int CKS_KeenSwim_height;
extern const unsigned int CKS_KeenSwim_size;
extern const unsigned char CKS_KeenSwim_data[];
extern const unsigned short CKS_KeenSwim_boxinfo[];
extern const unsigned int CKS_KeenSwim_SprSize;
extern const unsigned int CKS_KeenSwim_SprCount;
extern const unsigned int CKS_KeenSwim_SprData[];
extern const unsigned int CKS_PoisonSlug_width;
extern const unsigned int CKS_PoisonSlug_height;
extern const unsigned int CKS_PoisonSlug_size;
extern const unsigned char CKS_PoisonSlug_data[];
extern const unsigned short CKS_PoisonSlug_boxinfo[];
extern const unsigned int CKS_PoisonSlug_SprSize;
extern const unsigned int CKS_PoisonSlug_SprCount;
extern const unsigned int CKS_PoisonSlug_SprData[];
extern const unsigned int CKS_PoisonPoo_width;
extern const unsigned int CKS_PoisonPoo_height;
extern const unsigned int CKS_PoisonPoo_size;
extern const unsigned char CKS_PoisonPoo_data[];
extern const unsigned short CKS_PoisonPoo_boxinfo[];
extern const unsigned int CKS_PoisonPoo_SprSize;
extern const unsigned int CKS_PoisonPoo_SprCount;
extern const unsigned int CKS_PoisonPoo_SprData[];
extern const unsigned int CKS_MadMushroom_width;
extern const unsigned int CKS_MadMushroom_height;
extern const unsigned int CKS_MadMushroom_size;
extern const unsigned char CKS_MadMushroom_data[];
extern const unsigned short CKS_MadMushroom_boxinfo[];
extern const unsigned int CKS_MadMushroom_SprSize;
extern const unsigned int CKS_MadMushroom_SprCount;
extern const unsigned int CKS_MadMushroom_SprData[];
extern const unsigned int CKS_PLindsey_width;
extern const unsigned int CKS_PLindsey_height;
extern const unsigned int CKS_PLindsey_size;
extern const unsigned char CKS_PLindsey_data[];
extern const unsigned short CKS_PLindsey_boxinfo[];
extern const unsigned int CKS_PLindsey_SprSize;
extern const unsigned int CKS_PLindsey_SprCount;
extern const unsigned int CKS_PLindsey_SprData[];
extern const unsigned int CKS_Inchworm_width;
extern const unsigned int CKS_Inchworm_height;
extern const unsigned int CKS_Inchworm_size;
extern const unsigned char CKS_Inchworm_data[];
extern const unsigned short CKS_Inchworm_boxinfo[];
extern const unsigned int CKS_Inchworm_SprSize;
extern const unsigned int CKS_Inchworm_SprCount;
extern const unsigned int CKS_Inchworm_SprData[];
extern const unsigned int CKS_Foot_width;
extern const unsigned int CKS_Foot_height;
extern const unsigned int CKS_Foot_size;
extern const unsigned char CKS_Foot_data[];
extern const unsigned short CKS_Foot_boxinfo[];
extern const unsigned int CKS_Foot_SprSize;
extern const unsigned int CKS_Foot_SprCount;
extern const unsigned int CKS_Foot_SprData[];
extern const unsigned int CKS_TEater_width;
extern const unsigned int CKS_TEater_height;
extern const unsigned int CKS_TEater_size;
extern const unsigned char CKS_TEater_data[];
extern const unsigned short CKS_TEater_boxinfo[];
extern const unsigned int CKS_TEater_SprSize;
extern const unsigned int CKS_TEater_SprCount;
extern const unsigned int CKS_TEater_SprData[];
extern const unsigned int CKS_PVaper_width;
extern const unsigned int CKS_PVaper_height;
extern const unsigned int CKS_PVaper_size;
extern const unsigned char CKS_PVaper_data[];
extern const unsigned short CKS_PVaper_boxinfo[];
extern const unsigned int CKS_PVaper_SprSize;
extern const unsigned int CKS_PVaper_SprCount;
extern const unsigned int CKS_PVaper_SprData[];
extern const unsigned int CKS_TESmoke_width;
extern const unsigned int CKS_TESmoke_height;
extern const unsigned int CKS_TESmoke_size;
extern const unsigned char CKS_TESmoke_data[];
extern const unsigned short CKS_TESmoke_boxinfo[];
extern const unsigned int CKS_TESmoke_SprSize;
extern const unsigned int CKS_TESmoke_SprCount;
extern const unsigned int CKS_TESmoke_SprData[];
extern const unsigned int CKS_Egg_width;
extern const unsigned int CKS_Egg_height;
extern const unsigned int CKS_Egg_size;
extern const unsigned char CKS_Egg_data[];
extern const unsigned short CKS_Egg_boxinfo[];
extern const unsigned int CKS_Egg_SprSize;
extern const unsigned int CKS_Egg_SprCount;
extern const unsigned int CKS_Egg_SprData[];
extern const unsigned int CKS_EggParticles_width;
extern const unsigned int CKS_EggParticles_height;
extern const unsigned int CKS_EggParticles_size;
extern const unsigned char CKS_EggParticles_data[];
extern const unsigned short CKS_EggParticles_boxinfo[];
extern const unsigned int CKS_EggParticles_SprSize;
extern const unsigned int CKS_EggParticles_SprCount;
extern const unsigned int CKS_EggParticles_SprData[];
extern const unsigned int CKS_BBirdWalk_width;
extern const unsigned int CKS_BBirdWalk_height;
extern const unsigned int CKS_BBirdWalk_size;
extern const unsigned char CKS_BBirdWalk_data[];
extern const unsigned short CKS_BBirdWalk_boxinfo[];
extern const unsigned int CKS_BBirdWalk_SprSize;
extern const unsigned int CKS_BBirdWalk_SprCount;
extern const unsigned int CKS_BBirdWalk_SprData[];
extern const unsigned int CKS_BBirdFly_width;
extern const unsigned int CKS_BBirdFly_height;
extern const unsigned int CKS_BBirdFly_size;
extern const unsigned char CKS_BBirdFly_data[];
extern const unsigned short CKS_BBirdFly_boxinfo[];
extern const unsigned int CKS_BBirdFly_SprSize;
extern const unsigned int CKS_BBirdFly_SprCount;
extern const unsigned int CKS_BBirdFly_SprData[];
extern const unsigned int CKS_Dart_width;
extern const unsigned int CKS_Dart_height;
extern const unsigned int CKS_Dart_size;
extern const unsigned char CKS_Dart_data[];
extern const unsigned short CKS_Dart_boxinfo[];
extern const unsigned int CKS_Dart_SprSize;
extern const unsigned int CKS_Dart_SprCount;
extern const unsigned int CKS_Dart_SprData[];
extern const unsigned int CKS_Mimrock_width;
extern const unsigned int CKS_Mimrock_height;
extern const unsigned int CKS_Mimrock_size;
extern const unsigned char CKS_Mimrock_data[];
extern const unsigned short CKS_Mimrock_boxinfo[];
extern const unsigned int CKS_Mimrock_SprSize;
extern const unsigned int CKS_Mimrock_SprCount;
extern const unsigned int CKS_Mimrock_SprData[];
extern const unsigned int CKS_DopeFish_width;
extern const unsigned int CKS_DopeFish_height;
extern const unsigned int CKS_DopeFish_size;
extern const unsigned char CKS_DopeFish_data[];
extern const unsigned short CKS_DopeFish_boxinfo[];
extern const unsigned int CKS_DopeFish_SprSize;
extern const unsigned int CKS_DopeFish_SprCount;
extern const unsigned int CKS_DopeFish_SprData[];
extern const unsigned int CKS_LBubble_width;
extern const unsigned int CKS_LBubble_height;
extern const unsigned int CKS_LBubble_size;
extern const unsigned char CKS_LBubble_data[];
extern const unsigned short CKS_LBubble_boxinfo[];
extern const unsigned int CKS_LBubble_SprSize;
extern const unsigned int CKS_LBubble_SprCount;
extern const unsigned int CKS_LBubble_SprData[];
extern const unsigned int CKS_SBubble_width;
extern const unsigned int CKS_SBubble_height;
extern const unsigned int CKS_SBubble_size;
extern const unsigned char CKS_SBubble_data[];
extern const unsigned short CKS_SBubble_boxinfo[];
extern const unsigned int CKS_SBubble_SprSize;
extern const unsigned int CKS_SBubble_SprCount;
extern const unsigned int CKS_SBubble_SprData[];
extern const unsigned int CKS_MBubble_width;
extern const unsigned int CKS_MBubble_height;
extern const unsigned int CKS_MBubble_size;
extern const unsigned char CKS_MBubble_data[];
extern const unsigned short CKS_MBubble_boxinfo[];
extern const unsigned int CKS_MBubble_SprSize;
extern const unsigned int CKS_MBubble_SprCount;
extern const unsigned int CKS_MBubble_SprData[];
extern const unsigned int CKS_Schoolfish_width;
extern const unsigned int CKS_Schoolfish_height;
extern const unsigned int CKS_Schoolfish_size;
extern const unsigned char CKS_Schoolfish_data[];
extern const unsigned short CKS_Schoolfish_boxinfo[];
extern const unsigned int CKS_Schoolfish_SprSize;
extern const unsigned int CKS_Schoolfish_SprCount;
extern const unsigned int CKS_Schoolfish_SprData[];
extern const unsigned int CKS_Arachnut_width;
extern const unsigned int CKS_Arachnut_height;
extern const unsigned int CKS_Arachnut_size;
extern const unsigned char CKS_Arachnut_data[];
extern const unsigned short CKS_Arachnut_boxinfo[];
extern const unsigned int CKS_Arachnut_SprSize;
extern const unsigned int CKS_Arachnut_SprCount;
extern const unsigned int CKS_Arachnut_SprData[];
extern const unsigned int CKS_Swimsuit_width;
extern const unsigned int CKS_Swimsuit_height;
extern const unsigned int CKS_Swimsuit_size;
extern const unsigned char CKS_Swimsuit_data[];
extern const unsigned short CKS_Swimsuit_boxinfo[];
extern const unsigned int CKS_Swimsuit_SprSize;
extern const unsigned int CKS_Swimsuit_SprCount;
extern const unsigned int CKS_Swimsuit_SprData[];
extern const unsigned int CKS_Sprite_width;
extern const unsigned int CKS_Sprite_height;
extern const unsigned int CKS_Sprite_size;
extern const unsigned char CKS_Sprite_data[];
extern const unsigned short CKS_Sprite_boxinfo[];
extern const unsigned int CKS_Sprite_SprSize;
extern const unsigned int CKS_Sprite_SprCount;
extern const unsigned int CKS_Sprite_SprData[];
extern const unsigned int CKS_EBlast_width;
extern const unsigned int CKS_EBlast_height;
extern const unsigned int CKS_EBlast_size;
extern const unsigned char CKS_EBlast_data[];
extern const unsigned short CKS_EBlast_boxinfo[];
extern const unsigned int CKS_EBlast_SprSize;
extern const unsigned int CKS_EBlast_SprCount;
extern const unsigned int CKS_EBlast_SprData[];
extern const unsigned int CKS_Mine_width;
extern const unsigned int CKS_Mine_height;
extern const unsigned int CKS_Mine_size;
extern const unsigned char CKS_Mine_data[];
extern const unsigned short CKS_Mine_boxinfo[];
extern const unsigned int CKS_Mine_SprSize;
extern const unsigned int CKS_Mine_SprCount;
extern const unsigned int CKS_Mine_SprData[];
extern const unsigned int CKS_Skypest_width;
extern const unsigned int CKS_Skypest_height;
extern const unsigned int CKS_Skypest_size;
extern const unsigned char CKS_Skypest_data[];
extern const unsigned short CKS_Skypest_boxinfo[];
extern const unsigned int CKS_Skypest_SprSize;
extern const unsigned int CKS_Skypest_SprCount;
extern const unsigned int CKS_Skypest_SprData[];
extern const unsigned int CKS_Wormouth_width;
extern const unsigned int CKS_Wormouth_height;
extern const unsigned int CKS_Wormouth_size;
extern const unsigned char CKS_Wormouth_data[];
extern const unsigned short CKS_Wormouth_boxinfo[];
extern const unsigned int CKS_Wormouth_SprSize;
extern const unsigned int CKS_Wormouth_SprCount;
extern const unsigned int CKS_Wormouth_SprData[];
extern const unsigned int CKS_Lick_width;
extern const unsigned int CKS_Lick_height;
extern const unsigned int CKS_Lick_size;
extern const unsigned char CKS_Lick_data[];
extern const unsigned short CKS_Lick_boxinfo[];
extern const unsigned int CKS_Lick_SprSize;
extern const unsigned int CKS_Lick_SprCount;
extern const unsigned int CKS_Lick_SprData[];
extern const unsigned int CKS_Elevator_width;
extern const unsigned int CKS_Elevator_height;
extern const unsigned int CKS_Elevator_size;
extern const unsigned char CKS_Elevator_data[];
extern const unsigned short CKS_Elevator_boxinfo[];
extern const unsigned int CKS_Elevator_SprSize;
extern const unsigned int CKS_Elevator_SprCount;
extern const unsigned int CKS_Elevator_SprData[];
extern const unsigned int CKS_EFire_width;
extern const unsigned int CKS_EFire_height;
extern const unsigned int CKS_EFire_size;
extern const unsigned char CKS_EFire_data[];
extern const unsigned short CKS_EFire_boxinfo[];
extern const unsigned int CKS_EFire_SprSize;
extern const unsigned int CKS_EFire_SprCount;
extern const unsigned int CKS_EFire_SprData[];
extern const unsigned int CKS_Bounder_width;
extern const unsigned int CKS_Bounder_height;
extern const unsigned int CKS_Bounder_size;
extern const unsigned char CKS_Bounder_data[];
extern const unsigned short CKS_Bounder_boxinfo[];
extern const unsigned int CKS_Bounder_SprSize;
extern const unsigned int CKS_Bounder_SprCount;
extern const unsigned int CKS_Bounder_SprData[];
extern const unsigned int CKS_ThunderCloud_width;
extern const unsigned int CKS_ThunderCloud_height;
extern const unsigned int CKS_ThunderCloud_size;
extern const unsigned char CKS_ThunderCloud_data[];
extern const unsigned short CKS_ThunderCloud_boxinfo[];
extern const unsigned int CKS_ThunderCloud_SprSize;
extern const unsigned int CKS_ThunderCloud_SprCount;
extern const unsigned int CKS_ThunderCloud_SprData[];
extern const unsigned int CKS_LightningBolt_width;
extern const unsigned int CKS_LightningBolt_height;
extern const unsigned int CKS_LightningBolt_size;
extern const unsigned char CKS_LightningBolt_data[];
extern const unsigned short CKS_LightningBolt_boxinfo[];
extern const unsigned int CKS_LightningBolt_SprSize;
extern const unsigned int CKS_LightningBolt_SprCount;
extern const unsigned int CKS_LightningBolt_SprData[];
extern const unsigned int CKS_Berkeloid_width;
extern const unsigned int CKS_Berkeloid_height;
extern const unsigned int CKS_Berkeloid_size;
extern const unsigned char CKS_Berkeloid_data[];
extern const unsigned short CKS_Berkeloid_boxinfo[];
extern const unsigned int CKS_Berkeloid_SprSize;
extern const unsigned int CKS_Berkeloid_SprCount;
extern const unsigned int CKS_Berkeloid_SprData[];
extern const unsigned int CKS_Flame_width;
extern const unsigned int CKS_Flame_height;
extern const unsigned int CKS_Flame_size;
extern const unsigned char CKS_Flame_data[];
extern const unsigned short CKS_Flame_boxinfo[];
extern const unsigned int CKS_Flame_SprSize;
extern const unsigned int CKS_Flame_SprCount;
extern const unsigned int CKS_Flame_SprData[];


const unsigned int *CK_SpritePtrs[] = {
	(unsigned int*)CKS_Paddle_SprData, &CKS_Paddle_SprCount, (unsigned int*)CKS_Paddle_data, &CKS_Paddle_SprSize, (unsigned int*)CKS_Paddle_boxinfo, 
	(unsigned int*)CKS_Ball_SprData, &CKS_Ball_SprCount, (unsigned int*)CKS_Ball_data, &CKS_Ball_SprSize, (unsigned int*)CKS_Ball_boxinfo, 
	(unsigned int*)CKS_Demo_SprData, &CKS_Demo_SprCount, (unsigned int*)CKS_Demo_data, &CKS_Demo_SprSize, (unsigned int*)CKS_Demo_boxinfo, 
	(unsigned int*)CKS_Keen_SprData, &CKS_Keen_SprCount, (unsigned int*)CKS_Keen_data, &CKS_Keen_SprSize, (unsigned int*)CKS_Keen_boxinfo, 
	(unsigned int*)CKS_Stars_SprData, &CKS_Stars_SprCount, (unsigned int*)CKS_Stars_data, &CKS_Stars_SprSize, (unsigned int*)CKS_Stars_boxinfo, 
	(unsigned int*)CKS_Shot_SprData, &CKS_Shot_SprCount, (unsigned int*)CKS_Shot_data, &CKS_Shot_SprSize, (unsigned int*)CKS_Shot_boxinfo, 
	(unsigned int*)CKS_Droplets_SprData, &CKS_Droplets_SprCount, (unsigned int*)CKS_Droplets_data, &CKS_Droplets_SprSize, (unsigned int*)CKS_Droplets_boxinfo, 
	(unsigned int*)CKS_OneUp_SprData, &CKS_OneUp_SprCount, (unsigned int*)CKS_OneUp_data, &CKS_OneUp_SprSize, (unsigned int*)CKS_OneUp_boxinfo, 
	(unsigned int*)CKS_Shadows_SprData, &CKS_Shadows_SprCount, (unsigned int*)CKS_Shadows_data, &CKS_Shadows_SprSize, (unsigned int*)CKS_Shadows_boxinfo, 
	(unsigned int*)CKS_Soda_SprData, &CKS_Soda_SprCount, (unsigned int*)CKS_Soda_data, &CKS_Soda_SprSize, (unsigned int*)CKS_Soda_boxinfo, 
	(unsigned int*)CKS_TTGum_SprData, &CKS_TTGum_SprCount, (unsigned int*)CKS_TTGum_data, &CKS_TTGum_SprSize, (unsigned int*)CKS_TTGum_boxinfo, 
	(unsigned int*)CKS_CBar_SprData, &CKS_CBar_SprCount, (unsigned int*)CKS_CBar_data, &CKS_CBar_SprSize, (unsigned int*)CKS_CBar_boxinfo, 
	(unsigned int*)CKS_JBreaker_SprData, &CKS_JBreaker_SprCount, (unsigned int*)CKS_JBreaker_data, &CKS_JBreaker_SprSize, (unsigned int*)CKS_JBreaker_boxinfo, 
	(unsigned int*)CKS_Doughnut_SprData, &CKS_Doughnut_SprCount, (unsigned int*)CKS_Doughnut_data, &CKS_Doughnut_SprSize, (unsigned int*)CKS_Doughnut_boxinfo, 
	(unsigned int*)CKS_Icecream_SprData, &CKS_Icecream_SprCount, (unsigned int*)CKS_Icecream_data, &CKS_Icecream_SprSize, (unsigned int*)CKS_Icecream_boxinfo, 
	(unsigned int*)CKS_LWFlask_SprData, &CKS_LWFlask_SprCount, (unsigned int*)CKS_LWFlask_data, &CKS_LWFlask_SprSize, (unsigned int*)CKS_LWFlask_boxinfo, 
	(unsigned int*)CKS_Door_SprData, &CKS_Door_SprCount, (unsigned int*)CKS_Door_data, &CKS_Door_SprSize, (unsigned int*)CKS_Door_boxinfo, 
	(unsigned int*)CKS_RKey_SprData, &CKS_RKey_SprCount, (unsigned int*)CKS_RKey_data, &CKS_RKey_SprSize, (unsigned int*)CKS_RKey_boxinfo, 
	(unsigned int*)CKS_YKey_SprData, &CKS_YKey_SprCount, (unsigned int*)CKS_YKey_data, &CKS_YKey_SprSize, (unsigned int*)CKS_YKey_boxinfo, 
	(unsigned int*)CKS_BKey_SprData, &CKS_BKey_SprCount, (unsigned int*)CKS_BKey_data, &CKS_BKey_SprSize, (unsigned int*)CKS_BKey_boxinfo, 
	(unsigned int*)CKS_GKey_SprData, &CKS_GKey_SprCount, (unsigned int*)CKS_GKey_data, &CKS_GKey_SprSize, (unsigned int*)CKS_GKey_boxinfo, 
	(unsigned int*)CKS_KeyShadow_SprData, &CKS_KeyShadow_SprCount, (unsigned int*)CKS_KeyShadow_data, &CKS_KeyShadow_SprSize, (unsigned int*)CKS_KeyShadow_boxinfo, 
	(unsigned int*)CKS_NStunner_SprData, &CKS_NStunner_SprCount, (unsigned int*)CKS_NStunner_data, &CKS_NStunner_SprSize, (unsigned int*)CKS_NStunner_boxinfo, 
	(unsigned int*)CKS_ScoreBox_SprData, &CKS_ScoreBox_SprCount, (unsigned int*)CKS_ScoreBox_data, &CKS_ScoreBox_SprSize, (unsigned int*)CKS_ScoreBox_boxinfo, 
	(unsigned int*)CKS_MapKeen_SprData, &CKS_MapKeen_SprCount, (unsigned int*)CKS_MapKeen_data, &CKS_MapKeen_SprSize, (unsigned int*)CKS_MapKeen_boxinfo, 
	(unsigned int*)CKS_MapFoot_SprData, &CKS_MapFoot_SprCount, (unsigned int*)CKS_MapFoot_data, &CKS_MapFoot_SprSize, (unsigned int*)CKS_MapFoot_boxinfo, 
	(unsigned int*)CKS_MapFlagFlip_SprData, &CKS_MapFlagFlip_SprCount, (unsigned int*)CKS_MapFlagFlip_data, &CKS_MapFlagFlip_SprSize, (unsigned int*)CKS_MapFlagFlip_boxinfo, 
	(unsigned int*)CKS_MapFlagIdle_SprData, &CKS_MapFlagIdle_SprCount, (unsigned int*)CKS_MapFlagIdle_data, &CKS_MapFlagIdle_SprSize, (unsigned int*)CKS_MapFlagIdle_boxinfo, 
	(unsigned int*)CKS_KeenSwim_SprData, &CKS_KeenSwim_SprCount, (unsigned int*)CKS_KeenSwim_data, &CKS_KeenSwim_SprSize, (unsigned int*)CKS_KeenSwim_boxinfo, 
	(unsigned int*)CKS_PoisonSlug_SprData, &CKS_PoisonSlug_SprCount, (unsigned int*)CKS_PoisonSlug_data, &CKS_PoisonSlug_SprSize, (unsigned int*)CKS_PoisonSlug_boxinfo, 
	(unsigned int*)CKS_PoisonPoo_SprData, &CKS_PoisonPoo_SprCount, (unsigned int*)CKS_PoisonPoo_data, &CKS_PoisonPoo_SprSize, (unsigned int*)CKS_PoisonPoo_boxinfo, 
	(unsigned int*)CKS_MadMushroom_SprData, &CKS_MadMushroom_SprCount, (unsigned int*)CKS_MadMushroom_data, &CKS_MadMushroom_SprSize, (unsigned int*)CKS_MadMushroom_boxinfo, 
	(unsigned int*)CKS_PLindsey_SprData, &CKS_PLindsey_SprCount, (unsigned int*)CKS_PLindsey_data, &CKS_PLindsey_SprSize, (unsigned int*)CKS_PLindsey_boxinfo, 
	(unsigned int*)CKS_Inchworm_SprData, &CKS_Inchworm_SprCount, (unsigned int*)CKS_Inchworm_data, &CKS_Inchworm_SprSize, (unsigned int*)CKS_Inchworm_boxinfo, 
	(unsigned int*)CKS_Foot_SprData, &CKS_Foot_SprCount, (unsigned int*)CKS_Foot_data, &CKS_Foot_SprSize, (unsigned int*)CKS_Foot_boxinfo, 
	(unsigned int*)CKS_TEater_SprData, &CKS_TEater_SprCount, (unsigned int*)CKS_TEater_data, &CKS_TEater_SprSize, (unsigned int*)CKS_TEater_boxinfo, 
	(unsigned int*)CKS_PVaper_SprData, &CKS_PVaper_SprCount, (unsigned int*)CKS_PVaper_data, &CKS_PVaper_SprSize, (unsigned int*)CKS_PVaper_boxinfo, 
	(unsigned int*)CKS_TESmoke_SprData, &CKS_TESmoke_SprCount, (unsigned int*)CKS_TESmoke_data, &CKS_TESmoke_SprSize, (unsigned int*)CKS_TESmoke_boxinfo, 
	(unsigned int*)CKS_Egg_SprData, &CKS_Egg_SprCount, (unsigned int*)CKS_Egg_data, &CKS_Egg_SprSize, (unsigned int*)CKS_Egg_boxinfo, 
	(unsigned int*)CKS_EggParticles_SprData, &CKS_EggParticles_SprCount, (unsigned int*)CKS_EggParticles_data, &CKS_EggParticles_SprSize, (unsigned int*)CKS_EggParticles_boxinfo, 
	(unsigned int*)CKS_BBirdWalk_SprData, &CKS_BBirdWalk_SprCount, (unsigned int*)CKS_BBirdWalk_data, &CKS_BBirdWalk_SprSize, (unsigned int*)CKS_BBirdWalk_boxinfo, 
	(unsigned int*)CKS_BBirdFly_SprData, &CKS_BBirdFly_SprCount, (unsigned int*)CKS_BBirdFly_data, &CKS_BBirdFly_SprSize, (unsigned int*)CKS_BBirdFly_boxinfo, 
	(unsigned int*)CKS_Dart_SprData, &CKS_Dart_SprCount, (unsigned int*)CKS_Dart_data, &CKS_Dart_SprSize, (unsigned int*)CKS_Dart_boxinfo, 
	(unsigned int*)CKS_Mimrock_SprData, &CKS_Mimrock_SprCount, (unsigned int*)CKS_Mimrock_data, &CKS_Mimrock_SprSize, (unsigned int*)CKS_Mimrock_boxinfo, 
	(unsigned int*)CKS_DopeFish_SprData, &CKS_DopeFish_SprCount, (unsigned int*)CKS_DopeFish_data, &CKS_DopeFish_SprSize, (unsigned int*)CKS_DopeFish_boxinfo, 
	(unsigned int*)CKS_LBubble_SprData, &CKS_LBubble_SprCount, (unsigned int*)CKS_LBubble_data, &CKS_LBubble_SprSize, (unsigned int*)CKS_LBubble_boxinfo, 
	(unsigned int*)CKS_SBubble_SprData, &CKS_SBubble_SprCount, (unsigned int*)CKS_SBubble_data, &CKS_SBubble_SprSize, (unsigned int*)CKS_SBubble_boxinfo, 
	(unsigned int*)CKS_MBubble_SprData, &CKS_MBubble_SprCount, (unsigned int*)CKS_MBubble_data, &CKS_MBubble_SprSize, (unsigned int*)CKS_MBubble_boxinfo, 
	(unsigned int*)CKS_Schoolfish_SprData, &CKS_Schoolfish_SprCount, (unsigned int*)CKS_Schoolfish_data, &CKS_Schoolfish_SprSize, (unsigned int*)CKS_Schoolfish_boxinfo, 
	(unsigned int*)CKS_Arachnut_SprData, &CKS_Arachnut_SprCount, (unsigned int*)CKS_Arachnut_data, &CKS_Arachnut_SprSize, (unsigned int*)CKS_Arachnut_boxinfo, 
	(unsigned int*)CKS_Swimsuit_SprData, &CKS_Swimsuit_SprCount, (unsigned int*)CKS_Swimsuit_data, &CKS_Swimsuit_SprSize, (unsigned int*)CKS_Swimsuit_boxinfo, 
	(unsigned int*)CKS_Sprite_SprData, &CKS_Sprite_SprCount, (unsigned int*)CKS_Sprite_data, &CKS_Sprite_SprSize, (unsigned int*)CKS_Sprite_boxinfo, 
	(unsigned int*)CKS_EBlast_SprData, &CKS_EBlast_SprCount, (unsigned int*)CKS_EBlast_data, &CKS_EBlast_SprSize, (unsigned int*)CKS_EBlast_boxinfo, 
	(unsigned int*)CKS_Mine_SprData, &CKS_Mine_SprCount, (unsigned int*)CKS_Mine_data, &CKS_Mine_SprSize, (unsigned int*)CKS_Mine_boxinfo, 
	(unsigned int*)CKS_Skypest_SprData, &CKS_Skypest_SprCount, (unsigned int*)CKS_Skypest_data, &CKS_Skypest_SprSize, (unsigned int*)CKS_Skypest_boxinfo, 
	(unsigned int*)CKS_Wormouth_SprData, &CKS_Wormouth_SprCount, (unsigned int*)CKS_Wormouth_data, &CKS_Wormouth_SprSize, (unsigned int*)CKS_Wormouth_boxinfo, 
	(unsigned int*)CKS_Lick_SprData, &CKS_Lick_SprCount, (unsigned int*)CKS_Lick_data, &CKS_Lick_SprSize, (unsigned int*)CKS_Lick_boxinfo, 
	(unsigned int*)CKS_Elevator_SprData, &CKS_Elevator_SprCount, (unsigned int*)CKS_Elevator_data, &CKS_Elevator_SprSize, (unsigned int*)CKS_Elevator_boxinfo, 
	(unsigned int*)CKS_EFire_SprData, &CKS_EFire_SprCount, (unsigned int*)CKS_EFire_data, &CKS_EFire_SprSize, (unsigned int*)CKS_EFire_boxinfo, 
	(unsigned int*)CKS_Bounder_SprData, &CKS_Bounder_SprCount, (unsigned int*)CKS_Bounder_data, &CKS_Bounder_SprSize, (unsigned int*)CKS_Bounder_boxinfo, 
	(unsigned int*)CKS_ThunderCloud_SprData, &CKS_ThunderCloud_SprCount, (unsigned int*)CKS_ThunderCloud_data, &CKS_ThunderCloud_SprSize, (unsigned int*)CKS_ThunderCloud_boxinfo, 
	(unsigned int*)CKS_LightningBolt_SprData, &CKS_LightningBolt_SprCount, (unsigned int*)CKS_LightningBolt_data, &CKS_LightningBolt_SprSize, (unsigned int*)CKS_LightningBolt_boxinfo, 
	(unsigned int*)CKS_Berkeloid_SprData, &CKS_Berkeloid_SprCount, (unsigned int*)CKS_Berkeloid_data, &CKS_Berkeloid_SprSize, (unsigned int*)CKS_Berkeloid_boxinfo, 
	(unsigned int*)CKS_Flame_SprData, &CKS_Flame_SprCount, (unsigned int*)CKS_Flame_data, &CKS_Flame_SprSize, (unsigned int*)CKS_Flame_boxinfo, 
};
