
from os import listdir
from os.path import isfile, join

onlyfiles = [f.split('.',1)[0] for f in listdir(".") ]
onlyfiles.sort()

header = open("CK_BMPS.h", "w+")

header.write("// Bitmap externing generated by genbmphead.py\n\n")


for f in onlyfiles:
    if(f=="genbmphead" or f=="CK_BMPS"):
        continue
    f = f.replace('-','_')
    header.write("extern const unsigned char "+f+"[];\n")
    header.write("extern const unsigned int "+f+"_width;\n")
    header.write("extern const unsigned int "+f+"_height;\n")

header.write("\n\n")

header.write("const unsigned int *CK_BITMAP_MAPPER [] = {\n")
for f in onlyfiles:
    if(f=="genbmphead" or f=="CK_BMPS"):
        continue
    f = f.replace('-','_')
    header.write("\t"+f+", &"+f+"_width, &"+f+"_height,\n")

header.write("};\n\n")
header.close()
