// Bitmap externing generated by genbmphead.py

extern const unsigned char CK_BMP0006[];
extern const unsigned int CK_BMP0006_width;
extern const unsigned int CK_BMP0006_height;
extern const unsigned char CK_BMP0045[];
extern const unsigned int CK_BMP0045_width;
extern const unsigned int CK_BMP0045_height;
extern const unsigned char CK_BMP0088[];
extern const unsigned int CK_BMP0088_width;
extern const unsigned int CK_BMP0088_height;
extern const unsigned char CK_BMP0089[];
extern const unsigned int CK_BMP0089_width;
extern const unsigned int CK_BMP0089_height;
extern const unsigned char CK_BMP0090[];
extern const unsigned int CK_BMP0090_width;
extern const unsigned int CK_BMP0090_height;
extern const unsigned char CK_BMP0091[];
extern const unsigned int CK_BMP0091_width;
extern const unsigned int CK_BMP0091_height;
extern const unsigned char CK_BMP0092[];
extern const unsigned int CK_BMP0092_width;
extern const unsigned int CK_BMP0092_height;
extern const unsigned char CK_BMP0093[];
extern const unsigned int CK_BMP0093_width;
extern const unsigned int CK_BMP0093_height;
extern const unsigned char CK_BMP0094[];
extern const unsigned int CK_BMP0094_width;
extern const unsigned int CK_BMP0094_height;
extern const unsigned char CK_BMP0095[];
extern const unsigned int CK_BMP0095_width;
extern const unsigned int CK_BMP0095_height;
extern const unsigned char CK_BMP0096[];
extern const unsigned int CK_BMP0096_width;
extern const unsigned int CK_BMP0096_height;
extern const unsigned char CK_BMP0097[];
extern const unsigned int CK_BMP0097_width;
extern const unsigned int CK_BMP0097_height;
extern const unsigned char CK_BMP0098[];
extern const unsigned int CK_BMP0098_width;
extern const unsigned int CK_BMP0098_height;
extern const unsigned char CK_BMP0099[];
extern const unsigned int CK_BMP0099_width;
extern const unsigned int CK_BMP0099_height;
extern const unsigned char CK_BMP0100[];
extern const unsigned int CK_BMP0100_width;
extern const unsigned int CK_BMP0100_height;
extern const unsigned char CK_BMP0101[];
extern const unsigned int CK_BMP0101_width;
extern const unsigned int CK_BMP0101_height;
extern const unsigned char CK_BMP0102[];
extern const unsigned int CK_BMP0102_width;
extern const unsigned int CK_BMP0102_height;
extern const unsigned char CK_BMP0110[];
extern const unsigned int CK_BMP0110_width;
extern const unsigned int CK_BMP0110_height;
extern const unsigned char CK_BMP0111[];
extern const unsigned int CK_BMP0111_width;
extern const unsigned int CK_BMP0111_height;
extern const unsigned char CK_BMP0112[];
extern const unsigned int CK_BMP0112_width;
extern const unsigned int CK_BMP0112_height;
extern const unsigned char CK_BMP0113[];
extern const unsigned int CK_BMP0113_width;
extern const unsigned int CK_BMP0113_height;
extern const unsigned char CK_BMP0114[];
extern const unsigned int CK_BMP0114_width;
extern const unsigned int CK_BMP0114_height;
extern const unsigned char CK_BMP0115[];
extern const unsigned int CK_BMP0115_width;
extern const unsigned int CK_BMP0115_height;
extern const unsigned char CK_BMP0116[];
extern const unsigned int CK_BMP0116_width;
extern const unsigned int CK_BMP0116_height;
extern const unsigned char CK_BMP0117[];
extern const unsigned int CK_BMP0117_width;
extern const unsigned int CK_BMP0117_height;
extern const unsigned char CK_BMP0118[];
extern const unsigned int CK_BMP0118_width;
extern const unsigned int CK_BMP0118_height;
extern const unsigned char CK_BMP0119[];
extern const unsigned int CK_BMP0119_width;
extern const unsigned int CK_BMP0119_height;
extern const unsigned char CK_BMP0120[];
extern const unsigned int CK_BMP0120_width;
extern const unsigned int CK_BMP0120_height;
extern const unsigned char CK_BMP0121[];
extern const unsigned int CK_BMP0121_width;
extern const unsigned int CK_BMP0121_height;


const unsigned int *CK_BITMAP_MAPPER [] = {
	CK_BMP0006, &CK_BMP0006_width, &CK_BMP0006_height,
	CK_BMP0045, &CK_BMP0045_width, &CK_BMP0045_height,
	CK_BMP0088, &CK_BMP0088_width, &CK_BMP0088_height,
	CK_BMP0089, &CK_BMP0089_width, &CK_BMP0089_height,
	CK_BMP0090, &CK_BMP0090_width, &CK_BMP0090_height,
	CK_BMP0091, &CK_BMP0091_width, &CK_BMP0091_height,
	CK_BMP0092, &CK_BMP0092_width, &CK_BMP0092_height,
	CK_BMP0093, &CK_BMP0093_width, &CK_BMP0093_height,
	CK_BMP0094, &CK_BMP0094_width, &CK_BMP0094_height,
	CK_BMP0095, &CK_BMP0095_width, &CK_BMP0095_height,
	CK_BMP0096, &CK_BMP0096_width, &CK_BMP0096_height,
	CK_BMP0097, &CK_BMP0097_width, &CK_BMP0097_height,
	CK_BMP0098, &CK_BMP0098_width, &CK_BMP0098_height,
	CK_BMP0099, &CK_BMP0099_width, &CK_BMP0099_height,
	CK_BMP0100, &CK_BMP0100_width, &CK_BMP0100_height,
	CK_BMP0101, &CK_BMP0101_width, &CK_BMP0101_height,
	CK_BMP0102, &CK_BMP0102_width, &CK_BMP0102_height,
	CK_BMP0110, &CK_BMP0110_width, &CK_BMP0110_height,
	CK_BMP0111, &CK_BMP0111_width, &CK_BMP0111_height,
	CK_BMP0112, &CK_BMP0112_width, &CK_BMP0112_height,
	CK_BMP0113, &CK_BMP0113_width, &CK_BMP0113_height,
	CK_BMP0114, &CK_BMP0114_width, &CK_BMP0114_height,
	CK_BMP0115, &CK_BMP0115_width, &CK_BMP0115_height,
	CK_BMP0116, &CK_BMP0116_width, &CK_BMP0116_height,
	CK_BMP0117, &CK_BMP0117_width, &CK_BMP0117_height,
	CK_BMP0118, &CK_BMP0118_width, &CK_BMP0118_height,
	CK_BMP0119, &CK_BMP0119_width, &CK_BMP0119_height,
	CK_BMP0120, &CK_BMP0120_width, &CK_BMP0120_height,
	CK_BMP0121, &CK_BMP0121_width, &CK_BMP0121_height,
};

