// Bitmap externing generated by genbmphead.py

extern const unsigned char CK_BMP0006[];
extern const unsigned int CK_BMP0006_width;
extern const unsigned int CK_BMP0006_height;
extern const unsigned char CK_BMP0007[];
extern const unsigned int CK_BMP0007_width;
extern const unsigned int CK_BMP0007_height;
extern const unsigned char CK_BMP0008[];
extern const unsigned int CK_BMP0008_width;
extern const unsigned int CK_BMP0008_height;
extern const unsigned char CK_BMP0009[];
extern const unsigned int CK_BMP0009_width;
extern const unsigned int CK_BMP0009_height;
extern const unsigned char CK_BMP0010[];
extern const unsigned int CK_BMP0010_width;
extern const unsigned int CK_BMP0010_height;
extern const unsigned char CK_BMP0011[];
extern const unsigned int CK_BMP0011_width;
extern const unsigned int CK_BMP0011_height;
extern const unsigned char CK_BMP0012[];
extern const unsigned int CK_BMP0012_width;
extern const unsigned int CK_BMP0012_height;
extern const unsigned char CK_BMP0013[];
extern const unsigned int CK_BMP0013_width;
extern const unsigned int CK_BMP0013_height;
extern const unsigned char CK_BMP0014[];
extern const unsigned int CK_BMP0014_width;
extern const unsigned int CK_BMP0014_height;
extern const unsigned char CK_BMP0015[];
extern const unsigned int CK_BMP0015_width;
extern const unsigned int CK_BMP0015_height;
extern const unsigned char CK_BMP0016[];
extern const unsigned int CK_BMP0016_width;
extern const unsigned int CK_BMP0016_height;
extern const unsigned char CK_BMP0017[];
extern const unsigned int CK_BMP0017_width;
extern const unsigned int CK_BMP0017_height;
extern const unsigned char CK_BMP0018[];
extern const unsigned int CK_BMP0018_width;
extern const unsigned int CK_BMP0018_height;
extern const unsigned char CK_BMP0019[];
extern const unsigned int CK_BMP0019_width;
extern const unsigned int CK_BMP0019_height;
extern const unsigned char CK_BMP0020[];
extern const unsigned int CK_BMP0020_width;
extern const unsigned int CK_BMP0020_height;
extern const unsigned char CK_BMP0021[];
extern const unsigned int CK_BMP0021_width;
extern const unsigned int CK_BMP0021_height;
extern const unsigned char CK_BMP0022[];
extern const unsigned int CK_BMP0022_width;
extern const unsigned int CK_BMP0022_height;
extern const unsigned char CK_BMP0023[];
extern const unsigned int CK_BMP0023_width;
extern const unsigned int CK_BMP0023_height;
extern const unsigned char CK_BMP0024[];
extern const unsigned int CK_BMP0024_width;
extern const unsigned int CK_BMP0024_height;
extern const unsigned char CK_BMP0025[];
extern const unsigned int CK_BMP0025_width;
extern const unsigned int CK_BMP0025_height;
extern const unsigned char CK_BMP0026[];
extern const unsigned int CK_BMP0026_width;
extern const unsigned int CK_BMP0026_height;
extern const unsigned char CK_BMP0027[];
extern const unsigned int CK_BMP0027_width;
extern const unsigned int CK_BMP0027_height;
extern const unsigned char CK_BMP0028[];
extern const unsigned int CK_BMP0028_width;
extern const unsigned int CK_BMP0028_height;
extern const unsigned char CK_BMP0029[];
extern const unsigned int CK_BMP0029_width;
extern const unsigned int CK_BMP0029_height;
extern const unsigned char CK_BMP0030[];
extern const unsigned int CK_BMP0030_width;
extern const unsigned int CK_BMP0030_height;
extern const unsigned char CK_BMP0031[];
extern const unsigned int CK_BMP0031_width;
extern const unsigned int CK_BMP0031_height;
extern const unsigned char CK_BMP0032[];
extern const unsigned int CK_BMP0032_width;
extern const unsigned int CK_BMP0032_height;
extern const unsigned char CK_BMP0033[];
extern const unsigned int CK_BMP0033_width;
extern const unsigned int CK_BMP0033_height;
extern const unsigned char CK_BMP0034[];
extern const unsigned int CK_BMP0034_width;
extern const unsigned int CK_BMP0034_height;
extern const unsigned char CK_BMP0035[];
extern const unsigned int CK_BMP0035_width;
extern const unsigned int CK_BMP0035_height;
extern const unsigned char CK_BMP0036[];
extern const unsigned int CK_BMP0036_width;
extern const unsigned int CK_BMP0036_height;
extern const unsigned char CK_BMP0037[];
extern const unsigned int CK_BMP0037_width;
extern const unsigned int CK_BMP0037_height;
extern const unsigned char CK_BMP0038[];
extern const unsigned int CK_BMP0038_width;
extern const unsigned int CK_BMP0038_height;
extern const unsigned char CK_BMP0039[];
extern const unsigned int CK_BMP0039_width;
extern const unsigned int CK_BMP0039_height;
extern const unsigned char CK_BMP0040[];
extern const unsigned int CK_BMP0040_width;
extern const unsigned int CK_BMP0040_height;
extern const unsigned char CK_BMP0041[];
extern const unsigned int CK_BMP0041_width;
extern const unsigned int CK_BMP0041_height;
extern const unsigned char CK_BMP0042[];
extern const unsigned int CK_BMP0042_width;
extern const unsigned int CK_BMP0042_height;
extern const unsigned char CK_BMP0043[];
extern const unsigned int CK_BMP0043_width;
extern const unsigned int CK_BMP0043_height;
extern const unsigned char CK_BMP0044[];
extern const unsigned int CK_BMP0044_width;
extern const unsigned int CK_BMP0044_height;
extern const unsigned char CK_BMP0045[];
extern const unsigned int CK_BMP0045_width;
extern const unsigned int CK_BMP0045_height;
extern const unsigned char CK_BMP0046[];
extern const unsigned int CK_BMP0046_width;
extern const unsigned int CK_BMP0046_height;
extern const unsigned char CK_BMP0047[];
extern const unsigned int CK_BMP0047_width;
extern const unsigned int CK_BMP0047_height;
extern const unsigned char CK_BMP0048[];
extern const unsigned int CK_BMP0048_width;
extern const unsigned int CK_BMP0048_height;
extern const unsigned char CK_BMP0049[];
extern const unsigned int CK_BMP0049_width;
extern const unsigned int CK_BMP0049_height;
extern const unsigned char CK_BMP0050[];
extern const unsigned int CK_BMP0050_width;
extern const unsigned int CK_BMP0050_height;
extern const unsigned char CK_BMP0051[];
extern const unsigned int CK_BMP0051_width;
extern const unsigned int CK_BMP0051_height;
extern const unsigned char CK_BMP0052[];
extern const unsigned int CK_BMP0052_width;
extern const unsigned int CK_BMP0052_height;
extern const unsigned char CK_BMP0053[];
extern const unsigned int CK_BMP0053_width;
extern const unsigned int CK_BMP0053_height;
extern const unsigned char CK_BMP0054[];
extern const unsigned int CK_BMP0054_width;
extern const unsigned int CK_BMP0054_height;
extern const unsigned char CK_BMP0055[];
extern const unsigned int CK_BMP0055_width;
extern const unsigned int CK_BMP0055_height;
extern const unsigned char CK_BMP0056[];
extern const unsigned int CK_BMP0056_width;
extern const unsigned int CK_BMP0056_height;
extern const unsigned char CK_BMP0057[];
extern const unsigned int CK_BMP0057_width;
extern const unsigned int CK_BMP0057_height;
extern const unsigned char CK_BMP0058[];
extern const unsigned int CK_BMP0058_width;
extern const unsigned int CK_BMP0058_height;
extern const unsigned char CK_BMP0059[];
extern const unsigned int CK_BMP0059_width;
extern const unsigned int CK_BMP0059_height;
extern const unsigned char CK_BMP0060[];
extern const unsigned int CK_BMP0060_width;
extern const unsigned int CK_BMP0060_height;
extern const unsigned char CK_BMP0061[];
extern const unsigned int CK_BMP0061_width;
extern const unsigned int CK_BMP0061_height;
extern const unsigned char CK_BMP0062[];
extern const unsigned int CK_BMP0062_width;
extern const unsigned int CK_BMP0062_height;
extern const unsigned char CK_BMP0063[];
extern const unsigned int CK_BMP0063_width;
extern const unsigned int CK_BMP0063_height;
extern const unsigned char CK_BMP0064[];
extern const unsigned int CK_BMP0064_width;
extern const unsigned int CK_BMP0064_height;
extern const unsigned char CK_BMP0065[];
extern const unsigned int CK_BMP0065_width;
extern const unsigned int CK_BMP0065_height;
extern const unsigned char CK_BMP0066[];
extern const unsigned int CK_BMP0066_width;
extern const unsigned int CK_BMP0066_height;
extern const unsigned char CK_BMP0067[];
extern const unsigned int CK_BMP0067_width;
extern const unsigned int CK_BMP0067_height;
extern const unsigned char CK_BMP0068[];
extern const unsigned int CK_BMP0068_width;
extern const unsigned int CK_BMP0068_height;
extern const unsigned char CK_BMP0069[];
extern const unsigned int CK_BMP0069_width;
extern const unsigned int CK_BMP0069_height;
extern const unsigned char CK_BMP0070[];
extern const unsigned int CK_BMP0070_width;
extern const unsigned int CK_BMP0070_height;
extern const unsigned char CK_BMP0071[];
extern const unsigned int CK_BMP0071_width;
extern const unsigned int CK_BMP0071_height;
extern const unsigned char CK_BMP0072[];
extern const unsigned int CK_BMP0072_width;
extern const unsigned int CK_BMP0072_height;
extern const unsigned char CK_BMP0073[];
extern const unsigned int CK_BMP0073_width;
extern const unsigned int CK_BMP0073_height;
extern const unsigned char CK_BMP0074[];
extern const unsigned int CK_BMP0074_width;
extern const unsigned int CK_BMP0074_height;
extern const unsigned char CK_BMP0075[];
extern const unsigned int CK_BMP0075_width;
extern const unsigned int CK_BMP0075_height;
extern const unsigned char CK_BMP0076[];
extern const unsigned int CK_BMP0076_width;
extern const unsigned int CK_BMP0076_height;
extern const unsigned char CK_BMP0077[];
extern const unsigned int CK_BMP0077_width;
extern const unsigned int CK_BMP0077_height;
extern const unsigned char CK_BMP0078[];
extern const unsigned int CK_BMP0078_width;
extern const unsigned int CK_BMP0078_height;
extern const unsigned char CK_BMP0079[];
extern const unsigned int CK_BMP0079_width;
extern const unsigned int CK_BMP0079_height;
extern const unsigned char CK_BMP0088[];
extern const unsigned int CK_BMP0088_width;
extern const unsigned int CK_BMP0088_height;
extern const unsigned char CK_BMP0089[];
extern const unsigned int CK_BMP0089_width;
extern const unsigned int CK_BMP0089_height;
extern const unsigned char CK_BMP0090[];
extern const unsigned int CK_BMP0090_width;
extern const unsigned int CK_BMP0090_height;
extern const unsigned char CK_BMP0091[];
extern const unsigned int CK_BMP0091_width;
extern const unsigned int CK_BMP0091_height;
extern const unsigned char CK_BMP0092[];
extern const unsigned int CK_BMP0092_width;
extern const unsigned int CK_BMP0092_height;
extern const unsigned char CK_BMP0093[];
extern const unsigned int CK_BMP0093_width;
extern const unsigned int CK_BMP0093_height;
extern const unsigned char CK_BMP0094[];
extern const unsigned int CK_BMP0094_width;
extern const unsigned int CK_BMP0094_height;
extern const unsigned char CK_BMP0095[];
extern const unsigned int CK_BMP0095_width;
extern const unsigned int CK_BMP0095_height;
extern const unsigned char CK_BMP0096[];
extern const unsigned int CK_BMP0096_width;
extern const unsigned int CK_BMP0096_height;
extern const unsigned char CK_BMP0097[];
extern const unsigned int CK_BMP0097_width;
extern const unsigned int CK_BMP0097_height;
extern const unsigned char CK_BMP0098[];
extern const unsigned int CK_BMP0098_width;
extern const unsigned int CK_BMP0098_height;
extern const unsigned char CK_BMP0099[];
extern const unsigned int CK_BMP0099_width;
extern const unsigned int CK_BMP0099_height;
extern const unsigned char CK_BMP0100[];
extern const unsigned int CK_BMP0100_width;
extern const unsigned int CK_BMP0100_height;
extern const unsigned char CK_BMP0101[];
extern const unsigned int CK_BMP0101_width;
extern const unsigned int CK_BMP0101_height;
extern const unsigned char CK_BMP0102[];
extern const unsigned int CK_BMP0102_width;
extern const unsigned int CK_BMP0102_height;
extern const unsigned char CK_BMP0110[];
extern const unsigned int CK_BMP0110_width;
extern const unsigned int CK_BMP0110_height;
extern const unsigned char CK_BMP0111[];
extern const unsigned int CK_BMP0111_width;
extern const unsigned int CK_BMP0111_height;
extern const unsigned char CK_BMP0112[];
extern const unsigned int CK_BMP0112_width;
extern const unsigned int CK_BMP0112_height;
extern const unsigned char CK_BMP0113[];
extern const unsigned int CK_BMP0113_width;
extern const unsigned int CK_BMP0113_height;
extern const unsigned char CK_BMP0114[];
extern const unsigned int CK_BMP0114_width;
extern const unsigned int CK_BMP0114_height;
extern const unsigned char CK_BMP0115[];
extern const unsigned int CK_BMP0115_width;
extern const unsigned int CK_BMP0115_height;
extern const unsigned char CK_BMP0116[];
extern const unsigned int CK_BMP0116_width;
extern const unsigned int CK_BMP0116_height;
extern const unsigned char CK_BMP0117[];
extern const unsigned int CK_BMP0117_width;
extern const unsigned int CK_BMP0117_height;
extern const unsigned char CK_BMP0118[];
extern const unsigned int CK_BMP0118_width;
extern const unsigned int CK_BMP0118_height;
extern const unsigned char CK_BMP0119[];
extern const unsigned int CK_BMP0119_width;
extern const unsigned int CK_BMP0119_height;
extern const unsigned char CK_BMP0120[];
extern const unsigned int CK_BMP0120_width;
extern const unsigned int CK_BMP0120_height;
extern const unsigned char CK_BMP0121[];
extern const unsigned int CK_BMP0121_width;
extern const unsigned int CK_BMP0121_height;
extern const unsigned char CK_BMP0122[];
extern const unsigned int CK_BMP0122_width;
extern const unsigned int CK_BMP0122_height;
extern const unsigned char CK_BMP0123[];
extern const unsigned int CK_BMP0123_width;
extern const unsigned int CK_BMP0123_height;


const unsigned int *CK_BITMAP_MAPPER [] = {
	CK_BMP0006, &CK_BMP0006_width, &CK_BMP0006_height,
	CK_BMP0007, &CK_BMP0007_width, &CK_BMP0007_height,
	CK_BMP0008, &CK_BMP0008_width, &CK_BMP0008_height,
	CK_BMP0009, &CK_BMP0009_width, &CK_BMP0009_height,
	CK_BMP0010, &CK_BMP0010_width, &CK_BMP0010_height,
	CK_BMP0011, &CK_BMP0011_width, &CK_BMP0011_height,
	CK_BMP0012, &CK_BMP0012_width, &CK_BMP0012_height,
	CK_BMP0013, &CK_BMP0013_width, &CK_BMP0013_height,
	CK_BMP0014, &CK_BMP0014_width, &CK_BMP0014_height,
	CK_BMP0015, &CK_BMP0015_width, &CK_BMP0015_height,
	CK_BMP0016, &CK_BMP0016_width, &CK_BMP0016_height,
	CK_BMP0017, &CK_BMP0017_width, &CK_BMP0017_height,
	CK_BMP0018, &CK_BMP0018_width, &CK_BMP0018_height,
	CK_BMP0019, &CK_BMP0019_width, &CK_BMP0019_height,
	CK_BMP0020, &CK_BMP0020_width, &CK_BMP0020_height,
	CK_BMP0021, &CK_BMP0021_width, &CK_BMP0021_height,
	CK_BMP0022, &CK_BMP0022_width, &CK_BMP0022_height,
	CK_BMP0023, &CK_BMP0023_width, &CK_BMP0023_height,
	CK_BMP0024, &CK_BMP0024_width, &CK_BMP0024_height,
	CK_BMP0025, &CK_BMP0025_width, &CK_BMP0025_height,
	CK_BMP0026, &CK_BMP0026_width, &CK_BMP0026_height,
	CK_BMP0027, &CK_BMP0027_width, &CK_BMP0027_height,
	CK_BMP0028, &CK_BMP0028_width, &CK_BMP0028_height,
	CK_BMP0029, &CK_BMP0029_width, &CK_BMP0029_height,
	CK_BMP0030, &CK_BMP0030_width, &CK_BMP0030_height,
	CK_BMP0031, &CK_BMP0031_width, &CK_BMP0031_height,
	CK_BMP0032, &CK_BMP0032_width, &CK_BMP0032_height,
	CK_BMP0033, &CK_BMP0033_width, &CK_BMP0033_height,
	CK_BMP0034, &CK_BMP0034_width, &CK_BMP0034_height,
	CK_BMP0035, &CK_BMP0035_width, &CK_BMP0035_height,
	CK_BMP0036, &CK_BMP0036_width, &CK_BMP0036_height,
	CK_BMP0037, &CK_BMP0037_width, &CK_BMP0037_height,
	CK_BMP0038, &CK_BMP0038_width, &CK_BMP0038_height,
	CK_BMP0039, &CK_BMP0039_width, &CK_BMP0039_height,
	CK_BMP0040, &CK_BMP0040_width, &CK_BMP0040_height,
	CK_BMP0041, &CK_BMP0041_width, &CK_BMP0041_height,
	CK_BMP0042, &CK_BMP0042_width, &CK_BMP0042_height,
	CK_BMP0043, &CK_BMP0043_width, &CK_BMP0043_height,
	CK_BMP0044, &CK_BMP0044_width, &CK_BMP0044_height,
	CK_BMP0045, &CK_BMP0045_width, &CK_BMP0045_height,
	CK_BMP0046, &CK_BMP0046_width, &CK_BMP0046_height,
	CK_BMP0047, &CK_BMP0047_width, &CK_BMP0047_height,
	CK_BMP0048, &CK_BMP0048_width, &CK_BMP0048_height,
	CK_BMP0049, &CK_BMP0049_width, &CK_BMP0049_height,
	CK_BMP0050, &CK_BMP0050_width, &CK_BMP0050_height,
	CK_BMP0051, &CK_BMP0051_width, &CK_BMP0051_height,
	CK_BMP0052, &CK_BMP0052_width, &CK_BMP0052_height,
	CK_BMP0053, &CK_BMP0053_width, &CK_BMP0053_height,
	CK_BMP0054, &CK_BMP0054_width, &CK_BMP0054_height,
	CK_BMP0055, &CK_BMP0055_width, &CK_BMP0055_height,
	CK_BMP0056, &CK_BMP0056_width, &CK_BMP0056_height,
	CK_BMP0057, &CK_BMP0057_width, &CK_BMP0057_height,
	CK_BMP0058, &CK_BMP0058_width, &CK_BMP0058_height,
	CK_BMP0059, &CK_BMP0059_width, &CK_BMP0059_height,
	CK_BMP0060, &CK_BMP0060_width, &CK_BMP0060_height,
	CK_BMP0061, &CK_BMP0061_width, &CK_BMP0061_height,
	CK_BMP0062, &CK_BMP0062_width, &CK_BMP0062_height,
	CK_BMP0063, &CK_BMP0063_width, &CK_BMP0063_height,
	CK_BMP0064, &CK_BMP0064_width, &CK_BMP0064_height,
	CK_BMP0065, &CK_BMP0065_width, &CK_BMP0065_height,
	CK_BMP0066, &CK_BMP0066_width, &CK_BMP0066_height,
	CK_BMP0067, &CK_BMP0067_width, &CK_BMP0067_height,
	CK_BMP0068, &CK_BMP0068_width, &CK_BMP0068_height,
	CK_BMP0069, &CK_BMP0069_width, &CK_BMP0069_height,
	CK_BMP0070, &CK_BMP0070_width, &CK_BMP0070_height,
	CK_BMP0071, &CK_BMP0071_width, &CK_BMP0071_height,
	CK_BMP0072, &CK_BMP0072_width, &CK_BMP0072_height,
	CK_BMP0073, &CK_BMP0073_width, &CK_BMP0073_height,
	CK_BMP0074, &CK_BMP0074_width, &CK_BMP0074_height,
	CK_BMP0075, &CK_BMP0075_width, &CK_BMP0075_height,
	CK_BMP0076, &CK_BMP0076_width, &CK_BMP0076_height,
	CK_BMP0077, &CK_BMP0077_width, &CK_BMP0077_height,
	CK_BMP0078, &CK_BMP0078_width, &CK_BMP0078_height,
	CK_BMP0079, &CK_BMP0079_width, &CK_BMP0079_height,
	CK_BMP0088, &CK_BMP0088_width, &CK_BMP0088_height,
	CK_BMP0089, &CK_BMP0089_width, &CK_BMP0089_height,
	CK_BMP0090, &CK_BMP0090_width, &CK_BMP0090_height,
	CK_BMP0091, &CK_BMP0091_width, &CK_BMP0091_height,
	CK_BMP0092, &CK_BMP0092_width, &CK_BMP0092_height,
	CK_BMP0093, &CK_BMP0093_width, &CK_BMP0093_height,
	CK_BMP0094, &CK_BMP0094_width, &CK_BMP0094_height,
	CK_BMP0095, &CK_BMP0095_width, &CK_BMP0095_height,
	CK_BMP0096, &CK_BMP0096_width, &CK_BMP0096_height,
	CK_BMP0097, &CK_BMP0097_width, &CK_BMP0097_height,
	CK_BMP0098, &CK_BMP0098_width, &CK_BMP0098_height,
	CK_BMP0099, &CK_BMP0099_width, &CK_BMP0099_height,
	CK_BMP0100, &CK_BMP0100_width, &CK_BMP0100_height,
	CK_BMP0101, &CK_BMP0101_width, &CK_BMP0101_height,
	CK_BMP0102, &CK_BMP0102_width, &CK_BMP0102_height,
	CK_BMP0110, &CK_BMP0110_width, &CK_BMP0110_height,
	CK_BMP0111, &CK_BMP0111_width, &CK_BMP0111_height,
	CK_BMP0112, &CK_BMP0112_width, &CK_BMP0112_height,
	CK_BMP0113, &CK_BMP0113_width, &CK_BMP0113_height,
	CK_BMP0114, &CK_BMP0114_width, &CK_BMP0114_height,
	CK_BMP0115, &CK_BMP0115_width, &CK_BMP0115_height,
	CK_BMP0116, &CK_BMP0116_width, &CK_BMP0116_height,
	CK_BMP0117, &CK_BMP0117_width, &CK_BMP0117_height,
	CK_BMP0118, &CK_BMP0118_width, &CK_BMP0118_height,
	CK_BMP0119, &CK_BMP0119_width, &CK_BMP0119_height,
	CK_BMP0120, &CK_BMP0120_width, &CK_BMP0120_height,
	CK_BMP0121, &CK_BMP0121_width, &CK_BMP0121_height,
	CK_BMP0122, &CK_BMP0122_width, &CK_BMP0122_height,
	CK_BMP0123, &CK_BMP0123_width, &CK_BMP0123_height,
};

