// Sprite GBA sheet generated by ckspr2sheet bu John314
//
const unsigned int CKS_Paddle_SprSize = 128;
const unsigned int CKS_Paddle_SprCount = 1;
const unsigned int CKS_Paddle_SprData[] = {
	4, 0, 0, 0, // 
};
const unsigned int CKS_Ball_SprSize = 64;
const unsigned int CKS_Ball_SprCount = 1;
const unsigned int CKS_Ball_SprData[] = {
	0, 0, 0, 0, // 
};
const unsigned int CKS_Demo_SprSize = 1536;
const unsigned int CKS_Demo_SprCount = 4;
const unsigned int CKS_Demo_SprData[] = {
	6, 0, 0, 0, // 
	6, 32, 0, 8, // 
	5, 0, 16, 16, // 
	5, 32, 16, 20, // 
};
const unsigned int CKS_Keen_SprSize = 1280;
const unsigned int CKS_Keen_SprCount = 2;
const unsigned int CKS_Keen_SprData[] = {
	2, 0, 0, 0, // 
	5, 0, 32, 1248, // 
};
const unsigned int CKS_Stars_SprSize = 384;
const unsigned int CKS_Stars_SprCount = 2;
const unsigned int CKS_Stars_SprData[] = {
	1, 0, 0, 0, // 
	8, 16, 0, 12, // 
};
const unsigned int CKS_Shot_SprSize = 256;
const unsigned int CKS_Shot_SprCount = 1;
const unsigned int CKS_Shot_SprData[] = {
	1, 0, 0, 0, // 
};
const unsigned int CKS_Droplets_SprSize = 256;
const unsigned int CKS_Droplets_SprCount = 1;
const unsigned int CKS_Droplets_SprData[] = {
	1, 0, 0, 0, // 
};
const unsigned int CKS_ShadowOneUp_SprSize = 384;
const unsigned int CKS_ShadowOneUp_SprCount = 2;
const unsigned int CKS_ShadowOneUp_SprData[] = {
	1, 0, 0, 0, // 
	8, 16, 0, 4, // 
};
const unsigned int CKS_Shadow100_SprSize = 128;
const unsigned int CKS_Shadow100_SprCount = 1;
const unsigned int CKS_Shadow100_SprData[] = {
	4, 0, 0, 0, // 
};
const unsigned int CKS_Shadow200_SprSize = 128;
const unsigned int CKS_Shadow200_SprCount = 1;
const unsigned int CKS_Shadow200_SprData[] = {
	4, 0, 0, 0, // 
};
const unsigned int CKS_Shadow500_SprSize = 128;
const unsigned int CKS_Shadow500_SprCount = 1;
const unsigned int CKS_Shadow500_SprData[] = {
	4, 0, 0, 0, // 
};
const unsigned int CKS_Shadow1k_SprSize = 192;
const unsigned int CKS_Shadow1k_SprCount = 2;
const unsigned int CKS_Shadow1k_SprData[] = {
	4, 0, 0, 0, // 
	0, 16, 0, 2, // 
};
const unsigned int CKS_Shadow2k_SprSize = 192;
const unsigned int CKS_Shadow2k_SprCount = 2;
const unsigned int CKS_Shadow2k_SprData[] = {
	4, 0, 0, 0, // 
	0, 16, 0, 2, // 
};
const unsigned int CKS_Shadow5k_SprSize = 192;
const unsigned int CKS_Shadow5k_SprCount = 2;
const unsigned int CKS_Shadow5k_SprData[] = {
	4, 0, 0, 0, // 
	0, 16, 0, 2, // 
};
const unsigned int CKS_Shadow1up_SprSize = 384;
const unsigned int CKS_Shadow1up_SprCount = 2;
const unsigned int CKS_Shadow1up_SprData[] = {
	1, 0, 0, 0, // 
	8, 16, 0, 4, // 
};
const unsigned int CKS_ShadowStun_SprSize = 256;
const unsigned int CKS_ShadowStun_SprCount = 1;
const unsigned int CKS_ShadowStun_SprData[] = {
	1, 0, 0, 0, // 
};
const unsigned int CKS_Soda_SprSize = 256;
const unsigned int CKS_Soda_SprCount = 1;
const unsigned int CKS_Soda_SprData[] = {
	1, 0, 0, 0, // 
};
const unsigned int CKS_TTGum_SprSize = 256;
const unsigned int CKS_TTGum_SprCount = 1;
const unsigned int CKS_TTGum_SprData[] = {
	1, 0, 0, 0, // 
};
const unsigned int CKS_CBar_SprSize = 256;
const unsigned int CKS_CBar_SprCount = 1;
const unsigned int CKS_CBar_SprData[] = {
	1, 0, 0, 0, // 
};
const unsigned int CKS_JBreaker_SprSize = 256;
const unsigned int CKS_JBreaker_SprCount = 1;
const unsigned int CKS_JBreaker_SprData[] = {
	1, 0, 0, 0, // 
};
const unsigned int CKS_Doughnut_SprSize = 256;
const unsigned int CKS_Doughnut_SprCount = 1;
const unsigned int CKS_Doughnut_SprData[] = {
	1, 0, 0, 0, // 
};
const unsigned int CKS_Icecream_SprSize = 256;
const unsigned int CKS_Icecream_SprCount = 1;
const unsigned int CKS_Icecream_SprData[] = {
	1, 0, 0, 0, // 
};
const unsigned int CKS_LWFlask_SprSize = 256;
const unsigned int CKS_LWFlask_SprCount = 1;
const unsigned int CKS_LWFlask_SprData[] = {
	1, 0, 0, 0, // 
};
const unsigned int CKS_Door_SprSize = 1024;
const unsigned int CKS_Door_SprCount = 2;
const unsigned int CKS_Door_SprData[] = {
	10, 0, 0, 0, // 
	10, 0, 32, 8, // 
};
const unsigned int CKS_RKey_SprSize = 256;
const unsigned int CKS_RKey_SprCount = 1;
const unsigned int CKS_RKey_SprData[] = {
	1, 0, 0, 0, // 
};
const unsigned int CKS_YKey_SprSize = 256;
const unsigned int CKS_YKey_SprCount = 1;
const unsigned int CKS_YKey_SprData[] = {
	1, 0, 0, 0, // 
};
const unsigned int CKS_BKey_SprSize = 256;
const unsigned int CKS_BKey_SprCount = 1;
const unsigned int CKS_BKey_SprData[] = {
	1, 0, 0, 0, // 
};
const unsigned int CKS_GKey_SprSize = 256;
const unsigned int CKS_GKey_SprCount = 1;
const unsigned int CKS_GKey_SprData[] = {
	1, 0, 0, 0, // 
};
const unsigned int CKS_KeyShadow_SprSize = 256;
const unsigned int CKS_KeyShadow_SprCount = 1;
const unsigned int CKS_KeyShadow_SprData[] = {
	1, 0, 0, 0, // 
};
const unsigned int CKS_NStunner_SprSize = 256;
const unsigned int CKS_NStunner_SprCount = 1;
const unsigned int CKS_NStunner_SprData[] = {
	1, 0, 0, 0, // 
};
const unsigned int CKS_ScoreBoxDOS_SprSize = 3520;
const unsigned int CKS_ScoreBoxDOS_SprCount = 7;
const unsigned int CKS_ScoreBoxDOS_SprData[] = {
	7, 0, 0, 0, // 
	10, 64, 0, 32, // 
	9, 80, 0, 40, // 
	5, 0, 32, 44, // 
	5, 32, 32, 48, // 
	4, 64, 32, 52, // 
	0, 80, 32, 54, // 
};
const unsigned int CKS_ScoreBoxGBA_SprSize = 3840;
const unsigned int CKS_ScoreBoxGBA_SprCount = 8;
const unsigned int CKS_ScoreBoxGBA_SprData[] = {
	6, 0, 0, 0, // 
	6, 32, 0, 8, // 
	6, 64, 0, 16, // 
	6, 96, 0, 24, // 
	6, 128, 0, 32, // 
	6, 160, 0, 40, // 
	6, 192, 0, 48, // 
	1, 224, 0, 56, // 
};
const unsigned int CKS_MapKeen_SprSize = 256;
const unsigned int CKS_MapKeen_SprCount = 1;
const unsigned int CKS_MapKeen_SprData[] = {
	1, 0, 0, 0, // 
};
const unsigned int CKS_MapFoot_SprSize = 1280;
const unsigned int CKS_MapFoot_SprCount = 2;
const unsigned int CKS_MapFoot_SprData[] = {
	2, 0, 0, 0, // 
	9, 32, 0, 32, // 
};
const unsigned int CKS_MapFlag_SprSize = 1280;
const unsigned int CKS_MapFlag_SprCount = 2;
const unsigned int CKS_MapFlag_SprData[] = {
	2, 0, 0, 0, // 
	5, 0, 32, 176, // 
};
const unsigned int CKS_KeenSwim_SprSize = 1280;
const unsigned int CKS_KeenSwim_SprCount = 2;
const unsigned int CKS_KeenSwim_SprData[] = {
	2, 0, 0, 0, // 
	9, 32, 0, 96, // 
};
const unsigned int CKS_PoisonSlug_SprSize = 576;
const unsigned int CKS_PoisonSlug_SprCount = 4;
const unsigned int CKS_PoisonSlug_SprData[] = {
	1, 0, 0, 0, // 
	8, 16, 0, 32, // 
	4, 0, 16, 48, // 
	0, 16, 16, 64, // 
};
const unsigned int CKS_PoisonPoo_SprSize = 128;
const unsigned int CKS_PoisonPoo_SprCount = 1;
const unsigned int CKS_PoisonPoo_SprData[] = {
	4, 0, 0, 0, // 
};
const unsigned int CKS_MadMushroom_SprSize = 1024;
const unsigned int CKS_MadMushroom_SprCount = 1;
const unsigned int CKS_MadMushroom_SprData[] = {
	2, 0, 0, 0, // 
};
const unsigned int CKS_PLindsey_SprSize = 768;
const unsigned int CKS_PLindsey_SprCount = 2;
const unsigned int CKS_PLindsey_SprData[] = {
	10, 0, 0, 0, // 
	9, 16, 0, 32, // 
};
const unsigned int CKS_Inchworm_SprSize = 384;
const unsigned int CKS_Inchworm_SprCount = 2;
const unsigned int CKS_Inchworm_SprData[] = {
	1, 0, 0, 0, // 
	8, 16, 0, 16, // 
};
const unsigned int CKS_Foot_SprSize = 4032;
const unsigned int CKS_Foot_SprCount = 8;
const unsigned int CKS_Foot_SprData[] = {
	7, 0, 0, 0, // 
	9, 64, 0, 32, // 
	6, 0, 32, 36, // 
	6, 32, 32, 44, // 
	8, 64, 32, 52, // 
	5, 0, 48, 54, // 
	5, 32, 48, 58, // 
	0, 64, 48, 62, // 
};
const unsigned int CKS_TEater_SprSize = 1920;
const unsigned int CKS_TEater_SprCount = 4;
const unsigned int CKS_TEater_SprData[] = {
	2, 0, 0, 0, // 
	10, 32, 0, 144, // 
	5, 0, 32, 216, // 
	4, 32, 32, 252, // 
};
const unsigned int CKS_PVaper_SprSize = 256;
const unsigned int CKS_PVaper_SprCount = 1;
const unsigned int CKS_PVaper_SprData[] = {
	1, 0, 0, 0, // 
};
const unsigned int CKS_TESmoke_SprSize = 1600;
const unsigned int CKS_TESmoke_SprCount = 4;
const unsigned int CKS_TESmoke_SprData[] = {
	2, 0, 0, 0, // 
	9, 32, 0, 80, // 
	5, 0, 32, 100, // 
	0, 32, 32, 120, // 
};
const unsigned int CKS_CMember_SprSize = 960;
const unsigned int CKS_CMember_SprCount = 4;
const unsigned int CKS_CMember_SprData[] = {
	10, 0, 0, 0, // 
	9, 16, 0, 48, // 
	4, 0, 32, 72, // 
	0, 16, 32, 84, // 
};
const unsigned int CKS_Egg_SprSize = 768;
const unsigned int CKS_Egg_SprCount = 2;
const unsigned int CKS_Egg_SprData[] = {
	6, 0, 0, 0, // 
	5, 0, 16, 16, // 
};
const unsigned int CKS_EggParticles_SprSize = 64;
const unsigned int CKS_EggParticles_SprCount = 1;
const unsigned int CKS_EggParticles_SprData[] = {
	0, 0, 0, 0, // 
};
const unsigned int CKS_BBirdWalk_SprSize = 1024;
const unsigned int CKS_BBirdWalk_SprCount = 1;
const unsigned int CKS_BBirdWalk_SprData[] = {
	2, 0, 0, 0, // 
};
const unsigned int CKS_BBirdFly_SprSize = 2048;
const unsigned int CKS_BBirdFly_SprCount = 1;
const unsigned int CKS_BBirdFly_SprData[] = {
	7, 0, 0, 0, // 
};
const unsigned int CKS_Dart_SprSize = 256;
const unsigned int CKS_Dart_SprCount = 1;
const unsigned int CKS_Dart_SprData[] = {
	1, 0, 0, 0, // 
};
const unsigned int CKS_Mimrock_SprSize = 768;
const unsigned int CKS_Mimrock_SprCount = 2;
const unsigned int CKS_Mimrock_SprData[] = {
	10, 0, 0, 0, // 
	9, 16, 0, 128, // 
};
const unsigned int CKS_DopeFish_SprSize = 7040;
const unsigned int CKS_DopeFish_SprCount = 9;
const unsigned int CKS_DopeFish_SprData[] = {
	3, 0, 0, 0, // 
	10, 64, 0, 512, // 
	9, 80, 0, 576, // 
	10, 64, 32, 608, // 
	9, 80, 32, 672, // 
	6, 0, 64, 704, // 
	6, 32, 64, 768, // 
	1, 64, 64, 832, // 
	8, 80, 64, 864, // 
};
const unsigned int CKS_LBubble_SprSize = 256;
const unsigned int CKS_LBubble_SprCount = 1;
const unsigned int CKS_LBubble_SprData[] = {
	1, 0, 0, 0, // 
};
const unsigned int CKS_SBubble_SprSize = 64;
const unsigned int CKS_SBubble_SprCount = 1;
const unsigned int CKS_SBubble_SprData[] = {
	0, 0, 0, 0, // 
};
const unsigned int CKS_MBubble_SprSize = 256;
const unsigned int CKS_MBubble_SprCount = 1;
const unsigned int CKS_MBubble_SprData[] = {
	1, 0, 0, 0, // 
};
const unsigned int CKS_Schoolfish_SprSize = 128;
const unsigned int CKS_Schoolfish_SprCount = 1;
const unsigned int CKS_Schoolfish_SprData[] = {
	4, 0, 0, 0, // 
};
const unsigned int CKS_Arachnut_SprSize = 2560;
const unsigned int CKS_Arachnut_SprCount = 3;
const unsigned int CKS_Arachnut_SprData[] = {
	7, 0, 0, 0, // 
	5, 0, 32, 160, // 
	5, 32, 32, 180, // 
};
const unsigned int CKS_Swimsuit_SprSize = 1280;
const unsigned int CKS_Swimsuit_SprCount = 2;
const unsigned int CKS_Swimsuit_SprData[] = {
	2, 0, 0, 0, // 
	9, 32, 0, 16, // 
};
const unsigned int CKS_Sprite_SprSize = 576;
const unsigned int CKS_Sprite_SprCount = 4;
const unsigned int CKS_Sprite_SprData[] = {
	1, 0, 0, 0, // 
	8, 16, 0, 20, // 
	4, 0, 16, 30, // 
	0, 16, 16, 40, // 
};
const unsigned int CKS_EBlast_SprSize = 256;
const unsigned int CKS_EBlast_SprCount = 1;
const unsigned int CKS_EBlast_SprData[] = {
	1, 0, 0, 0, // 
};
const unsigned int CKS_Mine_SprSize = 576;
const unsigned int CKS_Mine_SprCount = 4;
const unsigned int CKS_Mine_SprData[] = {
	1, 0, 0, 0, // 
	8, 16, 0, 12, // 
	4, 0, 16, 18, // 
	0, 16, 16, 24, // 
};
const unsigned int CKS_Skypest_SprSize = 384;
const unsigned int CKS_Skypest_SprCount = 2;
const unsigned int CKS_Skypest_SprData[] = {
	1, 0, 0, 0, // 
	8, 16, 0, 56, // 
};
const unsigned int CKS_Wormouth_SprSize = 960;
const unsigned int CKS_Wormouth_SprCount = 4;
const unsigned int CKS_Wormouth_SprData[] = {
	6, 0, 0, 0, // 
	8, 32, 0, 96, // 
	5, 0, 16, 120, // 
	0, 32, 16, 168, // 
};
const unsigned int CKS_Lick_SprSize = 640;
const unsigned int CKS_Lick_SprCount = 2;
const unsigned int CKS_Lick_SprData[] = {
	6, 0, 0, 0, // 
	8, 32, 0, 120, // 
};
const unsigned int CKS_Elevator_SprSize = 896;
const unsigned int CKS_Elevator_SprCount = 3;
const unsigned int CKS_Elevator_SprData[] = {
	6, 0, 0, 0, // 
	1, 32, 0, 8, // 
	8, 48, 0, 12, // 
};
const unsigned int CKS_EFire_SprSize = 64;
const unsigned int CKS_EFire_SprCount = 1;
const unsigned int CKS_EFire_SprData[] = {
	0, 0, 0, 0, // 
};
const unsigned int CKS_Bounder_SprSize = 576;
const unsigned int CKS_Bounder_SprCount = 4;
const unsigned int CKS_Bounder_SprData[] = {
	1, 0, 0, 0, // 
	8, 16, 0, 28, // 
	4, 0, 16, 42, // 
	0, 16, 16, 56, // 
};
const unsigned int CKS_ThunderCloud_SprSize = 1536;
const unsigned int CKS_ThunderCloud_SprCount = 4;
const unsigned int CKS_ThunderCloud_SprData[] = {
	6, 0, 0, 0, // 
	6, 32, 0, 24, // 
	5, 0, 16, 48, // 
	5, 32, 16, 60, // 
};
const unsigned int CKS_LightningBolt_SprSize = 1728;
const unsigned int CKS_LightningBolt_SprCount = 6;
const unsigned int CKS_LightningBolt_SprData[] = {
	10, 0, 0, 0, // 
	9, 16, 0, 16, // 
	10, 0, 32, 24, // 
	9, 16, 32, 40, // 
	4, 0, 64, 48, // 
	0, 16, 64, 52, // 
};
const unsigned int CKS_Berkeloid_SprSize = 1920;
const unsigned int CKS_Berkeloid_SprCount = 4;
const unsigned int CKS_Berkeloid_SprData[] = {
	2, 0, 0, 0, // 
	9, 32, 0, 192, // 
	6, 0, 32, 240, // 
	8, 32, 32, 336, // 
};
const unsigned int CKS_Flame_SprSize = 640;
const unsigned int CKS_Flame_SprCount = 2;
const unsigned int CKS_Flame_SprData[] = {
	10, 0, 0, 0, // 
	4, 0, 32, 32, // 
};
const unsigned int CKS_EOL_SprSize = 64;
const unsigned int CKS_EOL_SprCount = 1;
const unsigned int CKS_EOL_SprData[] = {
	0, 0, 0, 0, // 
};
